- notices.md
> bluemazzoo-remove-note

- CONTRIBUTING.md
Add a bit of info to clarify that merged PRs won't be immediately reflected on GitHub.
> Clarify contributing

- topics/algolia/index.md
I am:
***********EDITING AN EXISTING TOPIC PAGE***********
instantsearch and instant-search are both used in a few repositories
> suggest instant-search topic too

- CONTRIBUTING.md
- README.md
Think some things got moved around in the README re: running tests. Fixing up the order here.
> Organize information about testing

- topics/php/index.md
I am:
The url currently directs you to a blank page on github https://github.com/topics/php.net. It should be the correct, secured url.
> Fixed broken php.net link and changed it to the secure version.

- topics/nodejs/index.md
> Unwrap Node.js description

- topics/probot/index.md
I am:
The probot-app topic is commonly used to denote individual apps that use the probot framework.
> add probot-app related topic

- test/test_helper.rb
- test/topics_test.rb
- topics/electron/index.md
- topics/perl/index.md
This branch:
- Adds some assertions so each URL is a full URL, starting with http or https.
- Fixes some URLs that did not conform.
- Shuffles some aliases around and adds a few related topics.
> Add tests to validate URL format

- test/topics_test.rb
- topics/awesome/index.md
- topics/css/index.md
- topics/cwl/index.md
This adds a couple tests to check for punctuation and the right format for 'released' and 'short_description' fields. It also corrects topics awesome, css, and cwl so the tests pass.
> Add some punctuation tests

- topics/monero/index.md
I am:
Monero is a cryptocurrency focused on privacy. A topic page should be curated.
At this moment, It has a volume of 43,033,600 dollars. Privacy is enabled by default that means nobody can see your informations. 
> Adding Monero

- topics/parsing/index.md
I am:
There are several topics related to language parsing and the subject can be confusing for newcomers. I thought making a general topic "parsing" with many aliases would help. The description and related topics will show up on all the aliased topic pages to provide context.
References:
- https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form
- http://savage.net.au/Ron/html/graphviz2.marpa/Lexing.and.Parsing.Overview.html
- https://en.wikipedia.org/wiki/Parsing#Computer_languages
- https://tomassetti.me/guide-parsing-algorithms-terminology/#parsingAlgorithms
> Add parsing topic

- topics/haxe/index.md
I am:
It's a programming language.
> Added Haxe

- topics/ubuntu/index.md
I am:
There are variations of Ubuntu using differrent desktop environments bydefault.
> Added some official Ubuntu-based distros

- topics/userscript/index.md
I am:
It's a platform. A lot of repos contain userscripts.
> Added userscript

- topics/cpp/index.md
I am:
Please explain why these changes are necessary: Inspired by labels on https://github.com/Microsoft/ChakraCore
> Add 2 aliases for 'cpp' topic

- topics/crystal/index.md
I am:
1. The topics `crystallang` and `crystal-language` are used by some Crystal projects. I added them to be consistent with Rust.
2. Crystal now has a GitHub URL at https://github.com/crystal-lang.
> Update Crystal topic

- topics-todo.md
- topics/latex/index.md
I am:
Please explain why you think this Topic page should be curated: It's LaTeX!
A logo is not provided. I'm waiting for a response in latex3/branding#1.
> Add LaTeX topic

- topics/gradle/index.md
I am:
Adding related topics to improve the page's content.
> Add Gradle related topics

- docs/API.md
This is not about topics themselves, therefore PR template checkboxes do not apply here :)
> Fix small typo in API doc

- topics/sdn/index.md
I am:
I recently read https://freedom-to-tinker.com/2018/02/12/software-defined-networking-whats-new-and-whats-new-for-tech-policy/ and wondered what projects were on GitHub. https://github.com/topics/sdn (183 + 19 for aliases). Seemed plausibly worth making the topic page a bit more informative.
> Add Software-defined networking

- topics-todo.md
- topics/terminal/index.md
I am:
***********EDITING AN EXISTING TOPIC OR COLLECTION************
> Add Terminal

- collections/tools-for-open-source/index.md
I am:
This was present on the old collections paged but missed in the import.
> tools-for-open-source: add shields

- collections/game-engines/index.md
- collections/programming-languages/index.md
These repositories had moved so imports were failing.
> collections: fix some repo redirects.

- test/topics_test.rb
- topics/game-off/index.md
Add a test (and improve URL tests generally) in the previous commit (2baacb2) which will catch errors like this in future.
> topics/game-off: fix bad URL.

- test/topics_test.rb
- test/topics_test_helper.rb
Rather than provide exceptions (https://github.com/github/explore/pull/192) let's allow these for all topics.
> test/topics*: increase max alias count.

- topics-todo.md
- topics/compiler/index.md
I am:
***********EDITING AN EXISTING TOPIC OR COLLECTION************
> Add complier

- collections/machine-learning/index.md
I am:
Added a reference to Apache Spark mirror repository on GitHub.
> Update index.md to include Apache Spark

- topics/ipfs/index.md
I am:
Makes things look better. Preview:
> Break up paragraphs in IPFS topic

- collections/clean-code-linters/index.md
I am:
This is a Git pre-receive hook to check commits and code style.  The tool
automatically detects most of the items on this page and executes them
accordingly on changed files.  Unlike the "pre-commit" project listed here,
pre-receive hooks run on the Git server side.  This has advantages and
disadvantages that are listed on the project's README.
**Please note: we will close your PR without comment …
> Add innogames/igcommit

- collections/software-development-tools/index.md
Checks that your Web applications/documents conform to the requirements in the HTML spec
I am:
**Note:** I am actually the maintainer for the validator/validator project
The Nu Html Checker is a static-analysis tool intended to help Web developers catch unintended mistakes in their HTML, CSS, and SVG content that might cause problems in the behavior of their Web applications, or performance problems, or usability problems.
> Add validator/validator

- docs/styleguide.md
I suggest the following changes for your consideration:
First, the grammar stuff:
-Updated periods to appear inside of quotes throughout (example: Never abbreviate "pull request".  to "Never abbreviate "pull request.")  This is per American style English, apparently; see https://style.mla.org/punctuation-and-quotation-marks/
-Corrected "it's" usage under the "Words that can be tricky / Open source section"  See http://www.dictionary.com/e/its-vs-its/. 
And a few small style changes throughout.
Overall, I really like this style guide.  It lays out the information in a nice, concise manner. It's certainly helpful to me as a new GitHub user!
Best and hope my suggested changes are helpful --
--Alissa
- [X ] I followed the contributing guidelines: …
> Suggesting some grammatical changes and style updates to styleguide.md

- collections/clean-code-linters/index.md
I am:
New and old Python tools could be presented
> Add Python black and flake8

- collections/software-development-tools/index.md
I am:
I saw that this tool is quite popular: https://github.com/klauscfhq/signale, I was wondering if it is worth adding? Let me know what you all think!
> Add Signale to Software-Development-Tools

- collections/social-impact/index.md
- [x ] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
I am:
- [x ] Suggesting edits to an existing topic or collection
- [x ] Content (and my changes are in `index.md`)
Suggested a change to point to our current repo since the older one is no longer actively maintained.
**Please note: we will close your PR without comment if you do not check the …
> Updated to HOT's new Tasking Manager repo

- collections/front-end-javascript-frameworks/index.md
Angular is modern version of AngularJS which is faster and future proof.
I am:
> Change AngularJS to Angular

- test/collections_test_helper.rb
> Increased the limit of collection items to 100

- collections/social-impact/index.md
I am:
cc: @damaneice @brandonrosage
> updates SI collection

- collections/front-end-javascript-frameworks/index.md
This list should include the [Mithril.js](https://mithril.js.org/) SPA framework. Considering the maturity of this framework, the active community behind it and its steady growth.
I am:
> add mithril.js framework

- topics/objective-c/index.md
> Duplicated "related" field on objective-c topic

- collections/game-engines/index.md
From now on, [Xenko is fully free and opensource](https://xenko.com/blog/xenko-opensource-mit/)
Please explain why these changes are necessary: Xenko is a big game-engine, recently fully published to GitHub with MIT license.
> Add Xenko Game Engine

- topics/duckduckgo/index.md
> github_url for Duckduckgo

- topics/lineageos/index.md
Please explain why you think this topic or collection should be curated:
> LineageOS Topic

- topics/cms/index.md
- topics/contentful/index.md
**I am both editing an existing topic and proposing a new one, so including both sections of the PR template below.** 
I'm really not sure how a privately owned startup which is *not* especially well known or popular managed to not only become a topic - despite [not meeting the requisite criteria](https://github.com/github/explore/blob/master/CONTRIBUTING.md#curating-a-new-topic-or-collection) - in particular, is *not* [widely used by repositories](https://help.github.com/articles/classifying-your-repository-with-topics/) other than its own - but also managed to spam itself as both the alias *and* related topic to every major programming language, and show up as the page header for [the topic of …
> Add cms as new topic

- topics/firefox/index.md
> Added some aliases and Wikipedia link
> Update firefox topic

- topics/webextension/index.md
> `chrome-extension` exists, `firefox-extension` is proposed in #342 for parity, but browser-agnostic standard emerged in the meantime and multiple project are tagged with `webextension` already. 
> Having a dedicated topic, would raise awareness among developers on how to write extensions that work in multiple browsers.
> Add webextension topic

- collections/game-engines/index.md
> Add Lance engine to the list.

- collections/github-browser-extensions/index.md
That pull request is a proposal to add `rgehan/octolenses-browser-extension` chrome extension to the `github-browser-extensions` collection.
This extension allows you to create exact filters on GitHub, that will nicely lay out all the information you need to be as productive as possible, but also to discover new repository as githunt do it.
> Add octolenses-browser-extension

- collections/social-impact/index.md
> adds Refuge Restrooms back in to the collection

- collections/github-browser-extensions/index.md
> https://github.com/xxhomey19/github-file-icon is great 👍
> [Collections] Add github-file-icon to extensions

- topics-todo.md
- topics/ai/index.md
> Add AI topic

- docs/styleguide.md
> Found a typo on string #018.
> Typo on #18

- collections/clean-code-linters/index.md
- collections/front-end-javascript-frameworks/index.md
- collections/game-engines/index.md
- collections/javascript-game-engines/index.md
- collections/machine-learning/index.md
Do the usual repository redirection dance.
> collections: fix redirects.

- collections/clean-code-linters/index.md
jimhester/lintr
> This change should be made, because R only has one linter, and it was missing from the list.
> Added the linter for R in the Clean Code Linters Collection.

- collections/devops-tools/index.md
- collections/github-browser-extensions/index.md
> Follow renamed collections.

- collections/tools-for-open-source/index.md
OSS CLI (for local CICD) + free cloud builds for OSS projects
> Pretty helpful for (mobile) CICD projects. Seems to warrant an inclusion.
> Added Bitrise

- topics/python/index.md
`Dutch spelling rules dictate that when used in combination with my first name, "van" is not capitalized: "Guido van Rossum".` - https://gvanrossum.github.io/
> Tussenvoegsel should be lowercase in Guido's name

- collections/software-in-science/index.md
Found it useful. Though needs much improvement.
> Added LaurentRDC/scikit-ued into software-in-science

- topics/react/index.md
> React does not use MVC

- topics/php/index.md
Updated the description of PHP to be more aligned with the one at php.net.
> Updated the description of PHP

- collections/social-impact/index.md
https://github.com/IEEEKeralaSection/rescuekerala is a repository made during the time of kerala floods which was responsible for saving the lives of a lot of people. I believe It will be a good addition to the Social Impact Collection Challenge
> Added rescuekerala repository

- README.md
- collections/learn-to-code/index.md
> Added two easiest resources for learning code.
> Addition of resources to Learn to Code

- collections/social-impact/index.md
Added global data ethics pledge and ethics resources from Data4Democracy organization.
The Data4Democracy/ethics-resources primarily stands as an ethics pledge for data scientists, data analysts, machine learning engineers, and others in the data science fields.  It is about helping to build a social movement that collectively works towards a more accountable, equitable, open, inclusive, and transparent data community. 
Additionally in the repo are resources, tools, working groups, and ethics principles.
> Added Data4Democracy/ethics-resources

- topics/fantasy-console/index.md
There are lots of repos flagged as **[`fantasy-console`](https://github.com/topics/fantasy-console?o=desc&s=stars)** on GitHub already. They are very popular in the game jam / retrogaming scenes.
> Add Fantasy Console topic 👾

- topics/fantasy-console/index.md
There should only be 10.
CC @leereilly https://github.com/github/explore/pull/415
> fantasy-console: reduce related topics.

- collections/front-end-javascript-frameworks/index.md
Framework based on jquery, html, and css that implements Material Design.
> Added a link to Daemonite's Material Design UI

- topics/twitter/index.md
> Twitter’s style guide recommends to always capitalise the word `Tweet`:
https://help.twitter.com/en/using-twitter#tweets
> Capitalise “Tweet” on Twitter topic

- collections/open-source-organizations/index.md
> Been reading more to learn about development.
> add godaddy open source blog

- topics/android/index.md
> Update index.md; Fixes short description

- topics/threejs/index.md
Three.js is a cross-browser JavaScript library and Application Programming Interface used to create and display animated 3D computer graphics in a web browser, it has a great popularity on Github and different developers are using this tag on their projects.
> Add new topic: Three.js

- collections/open-source-organizations/index.md
Add Cloudflare because their tools have been awesome for my open source projects.
> Add cloudflare.github.io to the Open Source Organizations collection

- collections/open-journalism/index.md
> On the datadesk/notebooks repository they have a summary of all the data analysis of the news they published on LA Times Data Desk. You can go to the specific files of the news by selecting it on the table displayed on README.
> adding LA Times Data Desk

- collections/software-development-tools/index.md
A minor fix, that updates the link pointing to the [**signale**](https://github.com/klaussinani/signale) repository:
```diff
- - klauscfhq/signale
+ - klaussinani/signale
```
> Update link to `signale` repository

- collections/front-end-javascript-frameworks/index.md
Lit Element is quicker was to get started with web development.
> Added lit-element, which is quick to get started

- collections/programming-languages/index.md
list of languages sorted according to star count as of 2018-12-06-16:00:00
Fixes https://github.com/github/explore/issues/479
The unsorted list of languages is now sorted, with the most starred language at the top. The other possible order would be alphabetical, but this has minor aesthetic problems (Apple/Swift etc) so I think this is tidier. Ideally the list would always be generated in a sorted order automatically, but that is an enhancement awaiting attention.
**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested …
> Update the list of languages, sorted by stars

- topics/zsh/index.md
Zsh is a commonly used shell with a large number of available scripts and extensions on GitHub (e.g. [OhMyZsh](https://github.com/robbyrussell/oh-my-zsh)).
> Add Zsh (Z shell) topic

- collections/front-end-javascript-frameworks/index.md
Adding aurelia
Aurelia is a highly used enterprise grade spa framework that should be included in this list.
> Adding aurelia to collection

- collections/programming-languages/index.md
> Added Loli to list
> Loli is the embeddable programming language, that founded last summer.
> Added Loli programming language

- collections/programming-languages/index.md
It has moved to a new organisation.
> collections/programming-languages: move loli repo.

- collections/github-pages-examples/index.md
> adding netflix

- collections/devops-tools/index.md
I've noticed the pipeline has been failing due to the [etsy/statsd](https://github.com/etsy/statsd) repository being transfered to [statsd/statsd](https://github.com/statsd/statsd) instead.
This pull request addresses the issue.
> Update statsd namespace

- collections/javascript-game-engines/index.md
PhysicsJS is no longer maintained.
The author said
It's been many years since writing this library. And I don't have time to dedicate to maintain it. On the up side, Matter.js has really 
stepped up and taken the spotlight of javascript physics. It has everything PhysicsJS has and more. :)
Check it at [PhysicsJS](https://github.com/wellcaffeinated/PhysicsJS)
> update PhysicsJS to matter-js

- collections/learn-to-code/index.md
The App Academy Open repository is an exemplary resource for learning to code.
> Add App Academy Open

- collections/javascript-game-engines/index.md
> three.js is a very prominent javascript 3D library/ game engine and I feel it would be appropriate to have it included in the collection
> Add three.js to index.md for JavaScript Game Engines Collection

- topics/visual-basic/index.md
> vb is a commonly used term for visual basic.
> Adding aliases for visual basic

- topics/visual-basic/index.md
Thanks @kolappannathan. VB and VB.NET are the same language.
If you would like some wiki:
> Although the ".NET" portion of the name was dropped in 2005 ...
Similarly, Mac OS X, OS X and macOS refer to the same OS.
> Add aliases for visual-basic

- collections/github-browser-extensions/index.md
> I found this github browser extension to be very useful so adding in the list.
> Added a very useful github browser extension

- topics/flutter/index.md
> New Flutter hompage is https://flutter.dev/ instead https://flutter.io/
> New Flutter hompage is https://flutter.dev instead

- topics/bosque/index.md
There are already some projects in github for this language and there is no direct topic to associate it with. 
- https://github.com/jakalkhalili/Bsquit
- https://github.com/bodiam/bosque-tic-tac-toe
- https://github.com/ariya/awesome-bosque
> including bosque topic specification

- topics/hackathon/index.md
The [`#hackathon` topic](https://github.com/topics/hackathon) has 2.5k associated repos.
> Add hackathon topic

- collections/hacking-minecraft/index.md
The existing link points to a different repository. Seems to make sense just to link to the new repo from the list.
> Update PocketMine-MP to new repo

- topics/java/index.md
- topics/javafx/index.md
> Better description, aliases, a better URL to point reader's to, and clarification of the existence of free and open source implementations.
> Update the Java topic overview

- topics/open-source/index.md
The [`#open-source` topic](https://github.com/topics/open-source) has 3.5k repositories.
> Add open source topic

- collections/open-journalism/index.md
WTFJHT is a great example of leveraging github in a journalistic effort. See [their FAQ](https://whatthefuckjusthappenedtoday.com/faq/#wtf-does-it-cost-to-run-this-thing) for the level of effort involved in pulling off this site.
> Add WTFJHT to open-journalism collection

- collections/programming-languages/index.md
> Zig is a cool programming language!
> Add Zig to Programming Languages

- topics/jwt/index.md
The [`#JWT` topic](https://github.com/topics/jwt) has 3.2k+ repos already
> Add JWT topic

- topics/raspberry-pi/index.md
The Raspberry Pi 4 was just released, so I edited the topic to include "raspberry-pi-4" as an alias. Also slightly modified the description.
Its important to keep the topic up to date (especially one as important as Raspberry Pi), so I've made some minor changes to reflect the recent release of the Raspberry Pi 4.
> Update for Raspberry Pi 4

- collections/choosing-projects/index.md
- collections/clean-code-linters/index.md
- collections/programming-languages/index.md
- collections/social-impact/index.md
> remove collection item "Your First GitHub Pull Request"

- collections/choosing-projects/index.md
> add youtube video of adding your first GitHub pull request

- collections/text-editors/index.md
https://github.com/mawww/kakoune
http://kakoune.org/
Hi. Kakoune is nice text-editor with powerful features centered around multi-selections.
> Add kakoune to the text-editors collection

- collections/text-editors/index.md
notepads is a new raising lightweight text editor written in UWP and it has gained tremendous attention and received tons of positive reviews already.
> Add Notepads to "Text Editors"

- collections/pixel-art-tools/index.md
> This pixel editor has a vi-like interface, which seems somewhat unique and potentially interesting for people who use vi(or vim).
> Add rx to pixelart tools

- collections/hacking-minecraft/index.md
> Add the hammer emoji :)

- collections/hacking-minecraft/index.md
> Revert "Add the hammer emoji :)"

- collections/hacking-minecraft/index.md
> Add hammer emoji back

- collections/hacking-minecraft/index.md
> Revert "Add hammer emoji back"

- topics/pihole/index.md
> Edited the name

- topics/ember/index.md
The existing description is old / outdated and from a time where MVVM was more to market towards people more familiar with backend or mobile-native environments. Since much of the web is component-oriented now, Ember is focusing on the "Components and Services" side of its architecture. The implementation details underneath that don't matter.
> Update the description of the ember.js topic

- topics/actions/index.md
> updates actions content

- collections/productivity-tools/index.md
> Rename collection item robbyrussell/oh-my-zsh  to ohmyzsh/ohmyzsh

- collections/teaching-computational-social-science/index.md
- [ x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
- [ x] Suggesting edits to an existing topic or collection
- [x ] Content (and my changes are in `index.md`)
> Further to requirement 2 above, I maintain these repositories and am affiliated with the projects but we are sharing the content for the wider community - the teaching and learning materials provided by the projects are offered, open source, for people to engage with. 
> Please replace this line with an explanation of why you …
> Adding two repositories

- collections/open-source-organizations/index.md
Reverts github/explore#1312
`apple/github.com/apple` is invalid
> Revert "Added links for Google, Apple"

- topics/wagtail/index.md
> Fixes formatting for Wagtail

- collections/text-editors/index.md
There's a duplicate entry in this text editors collection. This PR proposes removing it.
https://github.com/github/explore/pull/1348/files#diff-ac5445707c2ebdf94734e039115eee6bR19
> Remove duplicate entry

- collections/music/index.md
> Nuclear is a music player focused on streaming from free sources and aims to be a free replacement to Spotify.
> Add nukeop's Nuclear

- collections/text-editors/index.md
> add JetBrains/intellij-community to text-editors

- topics/scambaiting/index.md
> So people who find this topic can have better knowledge of the topic.
> Add topic: scambaiting

- topics/vanilla-js/index.md
I believe this topic should be curated because the topic already has over a thousand public repositories and it is well known in the web development world. In addition, projects using vanilla JavaScript also appeal to a certain crowd of people, a crowd separate from those using popular frameworks like React, Vue, or Angular.
> Add vanilla-js topic

- topics/credo/index.md
Credo is a static code analysis tool for the Elixir language with a
focus on teaching and code consistency.
- [ x ] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [ x ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
- [ x ] Curating a new topic or collection
- [ x ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ x ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ x ] All required fields in my `index.md` conform to the …
> Adds Credo topic

- topics/animal-crossing/index.md
I saw that the [animal-crossing topic](https://github.com/topics/animal-crossing) was gaining popularity because of the recent release of New Horizons. I thought it would be nice to provide some information about the series to folks who stumble across it or one of the related topics. 🌴
> Add animal-crossing topic

- collections/open-source-organizations/index.md
> Add project26 to opensource organizations

- collections/github-browser-extensions/index.md
> QuickReview for GitHub makes PR review easier and faster with helpful shortcuts to mark files as viewed, approve, merge PRs etc. :tada: :bulb:
> github-browser-extensions: Add browser extension for quick PR reviews

- collections/static-site-generators/index.md
> I've collected the most popular and well-maintained static site generators, eg. Jekyll, Hugo, Gatsby, Eleventy, etc... (a lot of which already have their own topics.)
> 
> Mainly based from my experience, [#static-site-generator](https://github.com/topics/static-site-generator), and Netlify's awesome pre-existing [staticgen.com](https://www.staticgen.com/) collection ([netlify/staticgen](https://github.com/netlify/staticgen)).
> 
> This is my first contribution here so feel free to request any changes or close this if I have the wrong idea of what a collection should be. :)
> 
> Thanks!
**Please note: we will close your PR without comment if you do …
> New collection: static site generators

- collections/pixel-art-tools/index.md
>It has most things you need to create pixel and animations. Its very light weight too. 
> Editing an existing collection - Pixel Art Tools

- collections/text-editors/index.md
Lua/Moonscript based GUI text editor
Howl is a mature, customizable, extensible, keyboard driven & fast GUI text editor.
> Adding Howl editor

- collections/open-source-organizations/index.md
> Revert "Add Uber's open source projects"

- collections/open-source-organizations/index.md
> I was looking through the list if orgs and their OSS projects and noticed that `Mozilla` was missing.
> Add mozilla to open source org list

- topics/c/index.md
> This tag may be used as by many repositories for C.
> Add "c-programming-language" as an aliase to C

- collections/open-source-organizations/index.md
Adding Zalando's Open Source Software site - https://opensource.zalando.com/
> Zalando's Open Source efforts should be discoverable via GitHub Topic search.
> Add Zalando GitHub OSS site

- topics/twitch/index.md
> spelling error in the short-description

- topics/creative-commons/index.md
> There are many projects on GitHub that use a Creative Commons license either standalone, or for non-source code assets along side their open-source license, and among these many of them refer to `creative-commons`, or `cc-*` in the list of topics. It also fits as a relevent topic given GitHub is where many open-source projects live.
> Added Topic for Creative Commons

- topics/bug-bounty/index.md
- topics/bugbounty/index.md
> 400 repositories concerned by this tag so it's interesting to add it. Moreover bugbounty take an important place in the security field. 
> Add Bugbounty topics

- topics-todo.md
- topics/gui/index.md
> Before the start of GUI, there was CLI (Command Line Interface). At that time, no one thought normal people could use a computer. In the course of time, more and more people have started using computer and this is what GUI has achieved. At present, neither icon nor description of GUI is attached on the page of GitHub topic "GUI". Thus, I would like to curate it.
**Please note: we will close your PR without comment if you do …
> Added gui topic

- topics/sql-server/index.md
> Added the aliases to index.md for discover ability. 
> Added sql-server aliasses

- topics-todo.md
- topics/sdk/index.md
The topic "SDK" is popular. Moreover, it is listed in the "topics-todo.md" file (https://github.com/github/explore/blob/master/topics-todo.md).
> New Topic: SDK

- collections/github-browser-extensions/index.md
> The repository formerly known as homerchen19/github-file-icon is now [homerchen19/github-file-icons](https://github.com/homerchen19/github-file-icons). This is breaking the collection import.
> Track renamed repo

- collections/load-testing/index.md
Added https://github.com/artilleryio/artillery to the list of load testing tools.
> Added artillery to load testing tools

- collections/pixel-art-tools/index.md
[Lospec](https://lospec.com/) is a popular pixel art site which hosts this pixel art editor.
> Added the repository for Lospec's Pixel Editor

- collections/made-in-africa/index.md
This is a collection of amazing resources compiled over 3 years of open source contributors and projects built by Nigerians for Global use.
`[made-in-nigeria](https://github.com/acekyd/made-in-nigeria)` is a collection of amazing resources compiled over 3 years of open source contributors and projects built by Nigerians for Global use.
I suggested a repository to the **Made in Africa** collection.
> Suggest the Made in Nigeria repository

- topics/bootstrap/index.md
Added aliases `bootstrap-5` and `bootstrap5` to `topics/bootstrap`
> Add bootstrap aliases

- collections/teaching-computational-social-science/index.md
This PR removes a repo that no longer exists and is causing the tests to fail.
> Remove deleted repo

- topics/powertoys/index.md
> Added topic PowerToys

- collections/devops-tools/index.md
Include several entries into the collection **DevOps Tools**, covering different DevOps practices such as building, deployment, and monitoring, among others, that come as alternatives to those already existing in the collection. The new entries refer to:
- Maven
- Gradle
- Prometheus
- Nagios
- Zabbix
- Consul
- Nomad
- Terraform
- Vault
- Spinnaker
> Update content on DevOps Tools collection

- collections/open-source-organizations/index.md
Include a couple of organizations that contribute a lot to the OSS community, a perfect fit for the collection **Open Source Organizations**. Such organizations are:
- New Relic
- Docker
> Update content on Open Source Organizations collection

- collections/government/index.md
Government of India open-sourced the main Android application that is used by millions of citizens in India and the government to manage COVID. This is being added to the Government collection.
> Added Govt of India's COVID management app

- topics/effector/index.md
Repository moved to an organisation
> effector moved to an organisation

- topics/pim/index.md
- **This is a short correction of this pull request: https://github.com/github/explore/pull/1869**
> fixing issues for topic pim - display name length limit

- collections/learn-to-code/index.md
Added [Roadmap to becoming an Artificial Intelligence Expert](https://github.com/AMAI-GmbH/AI-Expert-Roadmap)
I added the [Roadmap to becoming an Artificial Intelligence Expert](https://github.com/AMAI-GmbH/AI-Expert-Roadmap). It seems to be a quite new repository, but provides in my opinion a really nice intro to ML, Data Science and AI that really fits in the collection learn to code.
> Added AI Expert Roadmap

- collections/social-impact/index.md
Web application for organization of foodsaving groups worldwide
> The karrot project fits very well with the other projects.
> add yunity/karrot-frontend

- topics/linux/index.md
> i renamed `operating system` to `kernel` in linux topic. because linux is not an operating system and is an kernel.
> Linux: rename `operating system` to `kernel`

- collections/learn-to-code/index.md
> The [javascript-algorithms](https://github.com/trekhleb/javascript-algorithms) helps engineers to learn how to implement different data-structures and algorithms in JavaScript. This repository contains not only the code examples for each algorithm or a data-structure but also a short explanations with the links for further readings. It might be a good candidate for a "Learn to code" section.
> Add javascript-algorithms repository to "Learn to Code" collection

- topics/gis/index.md
GIS is an important topic. Many GIS software exists, even on GitHub to display/manage geographic data.
> Add a new topic for GIS

- topics/wsl/index.md
- [ x Content (and my changes are in `index.md`)
> Curate Windows Subsystem for Linux topic

- topics/photogrammetry/index.md
Addressing the growing popularity of photogrammetry-related projects.
> Add photogrammetry topic

- topics/point-cloud/index.md
Addressing the growing popularity of point-cloud processing.
> Add point-cloud topic

- topics/computer-vision/index.md
Some repositories use `computervision` tag. The pull request suggests to add this tag as an alias of `computer-vision`.
> Add computervision alias

- topics/computer-algebra/index.md
There should be a short explanation about this topic, as quite a lot of developers are unfamiliar with symbolic computations, it might clarify what the related repositories are about.
> New topic: computer-algebra

- topics/advent-of-code/index.md
> Advent of Code is getting bigger every year and connects programmers from different skill-levels all over the world. Some people choose to share their submission on GitHub with this typical topic. The curated topic page adds context and shows where people that are new to AoC should go to participate.
> Add Advent of Code

- collections/programming-languages/index.md
Senegal is a fairly new language developed by @Calamity210, it isnt popular or anything but seemed to have what it takes
> Added SenegalLang

- collections/programming-languages/index.md
**The EO language is an emerging initiative that already has 411 stars on GitHub.**
> Added the EO programming language to the list

- topics/parsing/index.md
> Changing the display name to match the topic name, so that the list on github/topics displays correctly. 
> Updating display name to match topic name.

- topics/threejs/index.md
> `three-js` and `threejs` appear together ,and they refers to the same lib.
> add an alias for threejs

- collections/made-in-india/index.md
> As the project is really cool and got 10k plus downloads in a short period of time. I would suggest adding this to the collection.
> Added `uvdesk/community-skeleton` to `made-in-india` collection

- collections/made-in-india/index.md
* kadalu as a project is started by kadalu.io which is also an Indian company. (All repos inside of kadalu org are also made-in-india)
* glusterfs on the other hand, is started by a company in US (started by Indian Origin founders), but all development happened in India.
**Please note: we will close your PR without …
> Add 'kadalu' and 'glusterfs' project to Made in India list

- collections/made-in-india/index.md
> GeekyAnts is a product development shop in India which is a the original developer and core contributor to NativeBase, a collection of UI widgets for React Native.
> Add geekyants/nativebase

- collections/clean-code-linters/index.md
> Add dotenv-linter

- collections/teaching-computational-social-science/index.md
Removing a now-deleted-or-made-private repo
> Remove deleted-or-private repo

- collections/government/index.md
[govCMS](https://github.com/govCMS) is a fully open-source content management system using [Drupal](https://drupal.org) with open-source web hosting via [Lagoon](https://github.com/uselagoon) built for government. The [Australian Government](https://www.govcms.gov.au) use it for all of their websites.
> Add govCMS

- topics/css-reset/index.md
>  A CSS reset is a style sheet that sets all CSS properties to their default values.
> :memo: CSS Reset Topic

- collections/css-frameworks/index.md
> A CSS framework is a set of tools that help you build websites. And People Spend Long Time Finding The Perfect One For Them
> 📝  New Collection CSS Frameworks

- collections/machine-learning/index.md
>I came across the hub opensource package and it is one of the best packages for the fastest unstructured dataset management for TensorFlow/PyTorch. Stream data real-time & version-control it, maintained by http://activeloop.ai. I felt adding a hub to the collection section will help users who work with large datasets (GB's) will have a way to load and process the data much faster. It was recently in #1trending as well.
> Add Hub to machine-learning collections

- collections/github-browser-extensions/index.md
Due To Some Issue In #2147. About A Pull Request Repository Deletion. This Change Was Not Been Able To Merged. All Credits Are To @Kajbo It was his idea. I have just implemented it. 😄
> This pr is only a clone of a already accepted pr: #2147  which had some issues
> 📝  Add github-vscode-icons

- topics/coregames/index.md
The canonical URL is with www
Just checked and the canonical url includes WWW
> Update CoreGames URL

- topics/remarkable-tablet/index.md
Most projects of the reMarkable community have adopted the use of the [remarkable-tablet](https://github.com/topic/remarkable-tablet) topic. Disclaimer: I do maintain software for the reMarkable tablets but I’m not affiliated in any way with the parent company.
> Curate the remarkable-tablet topic

- collections/github-pages-examples/index.md
One HTML Page Challenge has a cool example of allowing contributors to submit custom HTML that then gets hosted on the Github Pages as part of a challenge.
> Add One HTML Page Challenge

- collections/made-in-india/index.md
> Adding SigNoz, which is a newly launched Made-in-India project with a significant traction
> Add SigNoz

- collections/javascript-game-engines/index.md
> Taro is a new lightweight 3D game engine that was missing in the collection.
> Added Taro

- collections/made-in-india/index.md
---
> The Project I Have Added Is A New And Growing But Awesome Project. I used it and it was amazing. The community support was also very well.
---
> Add To Made In India Collection

- collections/made-in-india/index.md
> I think this topic should be added because we help each other to build new things, and more. Also, most of their repositories have 10k+ stars, and it teaches people how to learn algorithms, data structures, programming languages, and more.
> Add TheAlgorithms organization in Made in India collection

- collections/made-in-india/index.md
Pupilfirst LMS is a feature-rich open-source Learning Management System (LMS)
------------------------------------------------- 
Pupilfirst is a learning management system (LMS) built on Ruby on Rails and Rescript where learning is achieved through focused tasks, directed feedback, an iterative workflow, and community interaction.
> Add Pupilfirst LMS

- collections/made-in-italy/index.md
I've added another relevant repository made in italy
> Add ImageGoNord repository

- collections/game-engines/index.md
> It's a game framework, with 8.2k stars
Closes https://github.com/github/explore/pull/2288 (edit by @mikemcquaid)
> Add Bevy to the game engine list

- collections/made-in-ukraine/index.md
Add the following projects to `Made in Ukraine` collection:
- ttag --- Modern javascript i18n localization library based on ES6 tagged templates and the good old GNU gettext
- grpclib --- Pure-Python gRPC implementation for asyncio
I have added two projects which were initially made in Ukraine and became widely used worldwide. `ttag` gained a lot of attention and received code contributions from lots of people worldwide, whereas `grpclib` gained facebook attention and was used in [`facebook / idb`](https://github.com/facebook/idb)
> Add more projects to `Made in Ukraine` collection

- collections/css-frameworks/index.md
> I think frameworks is a single word
> ✏️ Fix Typo

- collections/software-defined-radio/index.md
> srsLTE is now srsRAN!

- collections/riscv-cores/index.md
New repositories with different approaches and experiments.
> New Cores and Experiments With Risc-V Cores

- topics/gameboy/index.md
> Popular topic with 669 *current* public repositories with multiple decades worth of research put towards it. Has an important place in preserving code for the future in the form of disassemblies. Also very unique in being very popular with individuals creating emulators.
> Add Game Boy topic

- collections/made-in-africa/index.md
> I have added a new repo for open source projects from Cote d'ivoire.
> add new project on made in africa collection

- collections/programming-languages/index.md
Beef is a language in active development on Github with 1.8k stars at the time this PR was created. There is lots of work being done with this language, primarily in game development. This project should get more visibility, as it fills a role for developers who prefer the syntax of language slike C# and Java, but requires compiled, high-performance applications with manual memory management.
> Update index.md with the language Beef

- topics/c/index.md
> Also add these synonyms for C language, where the community usually separates standard versions c lang in the projects
> Add C Aliases

- topics/hackathon-kit/index.md
- topics/hackathon-organiser/index.md
I am fixing the test suite failures to get the main branch back to green and passing
> Get test suite back to green

- topics/grafana/index.md
> No .png image because I did not get permission to use Grafana logo and I'm not sure how to go about doing that. If I can use the logo from https://en.wikipedia.org/wiki/Grafana#/media/File:Grafana_logo.svg then I'm happy to go back and add that.
There are currently 2,300+ public repos tagged with the grafana topic and it is a widely used piece of open source software.
> Add Grafana as a topic

- collections/music/index.md
It's a cool, useful, and free extension.
> Add music time

- topics/esolang/index.md
> This computer programming topic has a long history and a creative community. Having this topic explained and links attached would be nice.
> added esolang topic

- collections/clean-code-linters/index.md
- collections/game-engines/index.md
These repos have moved and need to be updated to their proper URLs so we can do an import.
> Update moved collection items

- collections/made-in-india/index.md
- collections/made-in-ukraine/index.md
- collections/music/index.md
- collections/text-editors/index.md
Following repository renames that are preventing successful import.
> Follow repository renames

- topics/fabricmc/index.md
> Many repositories that fall under this topic are not labeled with "fabricmc" but are labeled with similar topic names. I think it would be beneficial to add those as aliases.
> Add aliases for fabricmc

- topics/koans/index.md
> 
> Programming koans are a useful tool for learning a new language, dozens of repositories are already tagging themselves and each explains what 'programming koans' are. 
> Add description of Koans

- collections/made-in-india/index.md
> Add ToolJet/ToolJet to made-in-india list

- collections/made-in-cuba/index.md
This repository has gone private it seems.
> collections/made-in-cuba: remove private repository.

- collections/made-in-india/index.md
> I suggest to include Glific in the _Made in India_ collection because I believe it is an interesting project with considerable social impact with most of the contributors from India.
> Add glific/glific to Made in India collection

- collections/made-in-india/index.md
> An awesome project for made in india list
> added some of @gautamkrishnar's project to list of project's made in India

- collections/static-site-generators/index.md
> add franklin.jl to static site generators

- collections/made-in-cuba/index.md
All items must be GitHub entities, not URLs.
> Remove invalid item in Made in Cuba collection

- topics/e2ee/index.md
- topics/end-to-end-encryption/index.md
> An index.md file did not exist for either of these pre-existing well populated topics
> add index.md files to topics

- collections/made-in-vietnam/index.md
> two sites I frequent and find useful for developers. thanks @duythanhvn for created this helpful collection.
> update vi collection

- collections/hacking-minecraft/index.md
Paper - A High-performance Spigot fork that aims to fix gameplay and mechanics inconsistencies.
Fabric - A lightweight modding platform that updates much faster than Minecraft Forge.
Sodium - Sodium is a free and open-source optimization mod for the Minecraft client that improves frame rates, reduces micro-stutter, and fixes graphical issues in Minecraft. This mod can almost triple FPS in-game.
NoCom - Infamous "hack" that allowed certain players to record where everyone on a Minecraft world is at once on the server 2 Builders 2 Tools.
> These changes should be made because they cover more modern topics that involve "Hacking Minecraft."
> Please replace this …
> Add PaperMC, FabricMc, Sodium, and NoCom to Index.md in minecraft-hacking

- collections/demo-sources/index.md
"4 Edges" is, indeed, a demo. (And a popular one.)
> add "4 Edges"

- topics/aurelia/index.md
----
Removes all aliases of Aurelia.
Most are completely unused and others (like JSX) are not related to this.
> Remove Aurelia aliases

- collections/programming-languages/index.md
The list specifies languages that are **actively** being developed. I am no longer actively working on Lily, and do not expect to do so in the foreseeable future.
> Remove Lily from programming language list

- collections/php-framework/index.md
- collections/php-frameworks/index.md
> This is a new category that refers to PHP frameworks and it is very important as developer references
> This is a new category that refers to PHP frameworks and it is very important as developer references .
> Create PHP frameworks

- collections/riscv-cores/index.md
Add new RISC-V core project: A teaching-focused RISC-V CPU design used at UC Davis
> add new core  jlpteaching/dinocpu

- collections/made-in-india/index.md
> CircuitVerse seems like an actively maintained and a really handy tool for everyone who wants to play around with circuits
> add CircuitVerse/CircuitVerse

- collections/made-in-india/index.md
Added firstcontribution
> Help beginners to contribute to open source projects.
> Added FirstContributions project to list of project's made in India

- topics/python/index.md
> I explained the motive that led to Python's creation and mentioned the fact python is garbage-collected
> add info about Python

- collections/made-in-israel/index.md
> Create a "Made in Israel" collection

- topics/vpn/index.md
> Create VPN topic
> Create VPN topic
> Create VPN topic
> Create VPN topic

- collections/game-engines/index.md
> added Esenthel

- topics/kernel/index.md
> There are plenty of hobby kernels on github, and kernels are important pieces of software in everyone's life.
> Adding the 'kernel' topic

- collections/made-in-iran/index.md
> add project nipodb

- collections/made-in-iran/index.md
Reverts https://github.com/github/explore/pull/2555
> Revert "add project nipodb"

- collections/productivity-tools/index.md
- find is cumbersome and fd solves a lot of its issues. 
- ripgrep solves a lot of issues with grep.
- jq is a modern front-end developers go-to on the command line when dealing with json. 
- alacritty is fast reliable, extendible, and uses gpu acceleration - it's class. furthermore if windows/terminal is on this list so should alacritty.
**Please note: we will close your PR without comment if you do not check …
> Expanded productivity-tools collection

- topics/julia/index.md
- I am a member of the JuliaLang organization on GitHub but am on their list of "dormant" contributors.  I am not a maintainer, creator, contractor, or employee of the project.
The julialang topic is in use at https://github.com/topics/julialang
> Add julialang as an alias for julia

- topics-todo.md
> Mark web topic as complete

- .github/PULL_REQUEST_TEMPLATE.md
> Removed the separator, because only three dashes are enough to use. Commented out the text of thanks, but did not remove it. Then I added a few minor changes.
> PR template: commented out thanks

- collections/made-in-china/index.md
---
ctripcorp/apollo is now apolloconfig/apollo
> Update repo owner in Made in China collection

- topics/discord-js/index.md
---
**Added more aliases to the topic which will allow for it to be accessed broadly.** 
---
> Update discord-js index.md

- collections/demo-sources/index.md
---
> Just adding more releases as they get opensourced.
> add the recent two monad releases

- collections/made-in-iran/index.md
---
> mr-hashemi is an Iranian programming language
---
> Add mr-hashemi to made in iran collection

- topics/ukagaka/index.md
---
> Add a topic introduction.
I'm not quite sure if this counts as a stake: I'm just a regular ukagaka user/author, not the current maintainer of the ukagaka  project, so I guess not
I'm also not sure if it's against the rules to include a community link in a topic description, if so please remove it for me or let me know
---
> Add a topic: Ukagaka

- topics/windows-subsystem-for-android/index.md
---
This is an "Android emulator" that uses virtualization on Windows 11 devices, which is made by Microsoft.
---
> Add windows-subsystem-for-android topic

- collections/made-in-iran/index.md
---
> Moratab is an Iranian project
---
> Add moratab persian markdown editor

- collections/made-in-iran/index.md
---
> Pyabr is an Iranian operating system
---
> Add pyabr to made in iran collection

- collections/game-engines/index.md
---
[Solar2D](https://solar2d.com) is a widely used open-source game engine. I've been using it for almost 10 years myself and it deserves to be listed here in my humble opinion.
> Added Solar2D (formerly known as Corona SDK) to the list.

- collections/made-in-iran/index.md
add yummy project, a simple clone of snappfood.ir
- [ x ] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [ x ] Suggesting edits to an existing topic or collection
> add yummy project

- collections/game-engines/index.md
Hello, LittleJS Engine has nearly 2k likes after about 1 month.  I put a ton of work into making the best features to size ratio available.  Also now fully documented. Looking forward to seeing what others can do with it, thanks!
---
---
> Added LittleJS Engine

- topics/meilisearch/index.md
---
Disclaimer: MeiliSearch is the company I work for. I just wanted to add a few extra info about this topic. There is no logo as we're currently redesigning it.
---
> add `MeiliSearch` topic details

- collections/riscv-brazil/index.md
- collections/riscv-cores/index.md
---
Added Carlos de Paula Repository for RISC-V Core project.
---
> Added Carlos de Paula RISC-V Core

- collections/software-development-tools/index.md
---
> The newly added item provides cloud based software development environment.
---
> Add Gitpod to software-development-tools

- collections/made-in-turkey/index.md
---
> :turkey: is not same with :tr: so that updated emoji usage
---
> Updated Turkish flag emoji in Made in Turkey collection.

- collections/made-in-turkey/index.md
Adding one of the biggest deep learning Python packages ([sahi](https://github.com/obss/sahi)) that has over 40k downloads and 360+ stargazers.
Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.
> add obss/sahi to Turkey collection

- topics/toit/index.md
---
> Updated information for the Toit programming language.
---
> topics: update toit information

- topics/password-store/index.md
---
> It has ~300 repositories on GitHub and has a somewhat generic name, making finding details about it tricky on occasion.
---
> Add password-store topic

- topics/4d-component/index.md
- [ x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x ] Suggesting edits to an existing topic or collection
---
- [ x] Content (and my changes are in `index.md`)
---
> add more info on 4D components

- collections/made-in-turkey/index.md
---
> It's a great repository which is made in Turkey
---
> Add EasyProfiler into made-in-turkey collection

- topics/telegram/index.md
---
> I propose that the github_url gets added to the Telegram topic
> Add github_url to the Telegram topic

- topics/riot-games/index.md
---
> There was a typo in my previous pull request, #2868. Also added some aliases.
> Edits to topics/riot-games: typo correction and added aliases

- collections/music/index.md
---
I think the Orca project fits nicely into the collection, as it is used as a music sequencer with a solid community following.
I am unsure about the position inside the list. I just picked a random position. If there is a specific pattern I should follow, let me know.
> Add Orca sequencer project

- topics/advent-of-code/index.md
---
Topics [adventofcode](https://github.com/topics/adventofcode), [advent-of-code-2021](https://github.com/topics/advent-of-code-2021) and [aoc-2021](https://github.com/topics/aoc-2021) are also aliases for the global Advent of Code topic, so they should be added as well.
---
> Updated "Advent of Code" topic aliases

- topics/wagtail/index.md
---
Wagtail is changing its domain from wagtail.io to wagtail.org. See https://github.com/wagtail/wagtail/issues/7841.
> Update domain for Wagtail

- topics-todo.md
- topics/ansible-role/index.md
---
> It's on the `topics-todo.md` list
> ansible-role topic

- topics-todo.md
- topics/android-library/index.md
---
> It's on the `topics-todo.md` list
> android-library topic

- topics-todo.md
- topics/animation/index.md
---
> It's on the `topics-todo.md` list
> animation topic

- collections/pixel-art-tools/index.md
> add grafx2

- collections/software-defined-radio/index.md
> add some applications for sdr hardware

- collections/software-development-tools/index.md
> shell checker and interface builder

- topics/microservice/index.md
---
> microservice has 6,670 active public repositories.
---
> microservice topic

- collections/programming-languages/index.md
> add tcc, and basic

- collections/music/index.md
> add more music production software

- topics-todo.md
- topics/ui/index.md
---
>Please replace this line with an explanation of why you think this topic or collection should be curated.
> Microservice already has a topic page now.
---
> Update topics-todo.md and added topic ui

- collections/open-source-organizations/index.md
---
> This repository was deleted or taken private and is failing our builds.
---
> Remove inaccessible repository

- topics/umbraco/index.md
---
Adds related topics for recent and upcoming Umbraco versions: `umbraco-v9` and `umbraco-v10`.
The reason for these separate topic tags is due to underlying architecture changes with ASP.NET and Umbraco's support of the platform. Umbraco 9 supports .NET 5 _(TAFKA ".NET Core")_ - previous versions were on the .NET Framework v4.7, and with Umbraco 10 it will support .NET 6. The use of these topics will help the community and ecosystem to flag the supported platforms.
---
> Umbraco topic update

- collections/text-editors/index.md
> add apache/netbeans to text-editors

- topics/portugol/index.md
---
> Portugol is a base to learn programming basics in Brazil, so I think to add this topic to help people to find projects and share knowledge.
> Add Portugol topic

- topics/rails/index.md
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
note: Rails 4 and 5 got EOL'd and so there are less number of repos in these topics.
- [rails4](https://github.com/topics/rails4): 66 public repositories
- [rails5](https://github.com/topics/rails5): 1,203 public repositories
- [rails6](https://github.com/topics/rails6): 413 public repositories
- [rails7](https://github.com/topics/rails7): 45 public repositories
n/a
n/a
> Update aliases for rails (adding rails 6/7 besides rails 4/5)

- collections/programming-languages/index.md
---
> Gwion is an actively maintained programming language on GitHub that is designed for creating music.
> Add the Gwion programming language

- collections/made-in-africa/index.md
---
> These are some of the useful open source projects built in Africans by Africans. 
---
> Update made-in-africa GitHub collection

- topics/chrome-extension/index.md
---
- Add `google-chrome-extension` & `extension-chrome` as aliases to the topic
- The majority of repositories using these aliases are referring to the same thing
- Correct the release date of Chrome extensions
- They were released with this [blog post](https://chrome.googleblog.com/2010/01/over-1500-new-features-for-google.html) on January 25, 2010.
- Update the `short_description`
- It previously mentioned Google when Chrome extensions are not necessarily Google-specific.
- Reworded to sound a bit better.
- Update `url` to the official Chrome extension documentation page
- The previous link, the Chrome Web Store, is separate from just simply Chrome extensions
- Remove the Wikipedia URL
- The wiki page was primarily about …
> Update Chrome extension topic

- collections/made-in-brazil/index.md
---
An application inspired by cz-cli (commitzen) which can be used in any project besides NodeJS, made with Rust, and can be customized.
---
> Add alt-art/commit to collection

- collections/open-data/index.md
> Add whosonfirst-data/whosonfirst-data

- collections/open-source-mlops/index.md
---
> Several of the repositories in the `open-source-mlops` collection have been renamed.
---
> Correct renamed repositories

- collections/made-in-india/index.md
Test at scale - TAS
TAS helps you accelerate your testing, shorten job times and get faster feedback on code changes, manage flaky tests and keep master green at all times.
---
---
> Added LambdaTest/test-at-scale

- topics/f-droid/index.md
---
> Some useful information added in the F-Droid index.md file.
---
> F-Droid index.md improved

- collections/choosing-projects/index.md
---
It's no longer being maintained.
---
> Remove hoodie

- topics/redis/index.md
...as it was transferred a couple of years ago.
^ I am affiliated with the project as a maintainer :)
---
Explanation:
A couple of years ago the creator and maintainer of Redis, Salvatore Sanfilippo, had stepped down. As a result, the project was moved to the Redis GitHub org and is maintained there. GitHub redirects from the original to the new destination automatically, so finding the project isn't an issue.
That said. I've read the contribution guidelines and have waited for "someone to improve" this topic. I guess I could ask a community member that isn't a maintainer/employee/contractor to submit this PR on my behalf, but I feel this is a tad redundant :) The proposed change is technically correct (the best kind of …
> Updates Redis repository's URL

- topics/openui5/index.md
---
The OpenUI5 framework is a maintained JavaScript framework by SAP SE and is popular by business customers.
> Added OpenUI5 framework

- topics/no-code/index.md
A popular and quickly growing topic that should be included in the authoritative list on GitHub. I can contribute an agnostic logo if the topic is accepted.
---
---
> Create the "no-code" topic

- .github/workflows/conflict.yml
- .github/workflows/lint.yml
- .github/workflows/templates/conflict.md
- .github/workflows/test.yml
This PR:
- Adds an action to auto comment when a PR author does not check the conflict of interest checkbox
> Add conflict of interest check

- test/collections_test.rb
- test/collections_test_helper.rb
- test/test_helper.rb
This PR:
- Makes sure that we're subbing out `.` chars
- correctly converts the strings back so that cache lookups work
- counts and reports hits to the REST api
> Make sure that we're subbing out 'dot' chars as well

- .github/workflows/collections-renames.yml
- test/collections_test.rb
- test/collections_test_helper.rb
This PR:
- Adds an action that will auto fix renamed collection items and commit them back to `main`
> Autocorrect collection items

- test/collections_test.rb
- Update
- Add collection autofixer action
- Skip tests when autocorrecting
> Skip tests when autocorrecting

- collections/pixel-art-tools/index.md
---
I think the project I added to the collection for pixel art tools is fair and nice.
---
> Added quality entry to col. list for PA tools

- .github/workflows/collections-renames.yml
- collections/ai-model-zoos/index.md
- test/collections_test.rb
- test/collections_test_helper.rb
Updates the action and the test to support autofixing of removed collection items
> Support removing collection items with autofix action

- topics/nvd/index.md
---
As a three-letter acronym, NVD is often used in the security community and tagged in repos.  This will allow for easier searching and understanding of the data the repos are using 
> Create NVD Topic 

- topics/cve/index.md
- topics/nvd/index.md
---
CVE is a well-known acronym for Common Vulnerabilities and Exposures and has over 600 repos tagged so this will help with some basic information and links.
> Create CVE Topic

- topics/mcfunction/index.md
---
`mcfunction` has become a fairly known language since it was created back in 2018. There are currently 150 repositories with this topic, alongside 169 repositories using the language.
---
> Add mcfunction topic

- topics/bugbounty/index.md
---
`bug-bounty` and `bugbounty` are the same thing
> Move `bug-bounty` from `related` to `alias`

- topics/software-challenge-germany/index.md
---
> The previous description was insufficient in one regard and had an error in anotherone, which should be corrected herewith.
---
> Description improved and typo removed

- collections/game-engines/index.md
Inform7 is a game engine to create interactive fiction games.
---
---
> Added inform7 repo

- collections/made-in-iran/index.md
---
> I tried to add some useful Iranian open source projects. hope enjoy.
> Update index.md in collection/made-in-iran

- collections/learn-to-code/index.md
One check didn't pass because I'm actually editing one line on the index.md and not addind a new one at the end -_-
---
> Webgems repository changed so it would be useful to change it to the new one
---
> Updated webgems repository in 'learn to code'

- collections/programming-languages/index.md
Carbon language is open sourced on GitHub via https://9to5google.com/2022/07/19/carbon-programming-language-google-cpp/
---
Google has open sourced Carbon language on GitHub see citation: https://9to5google.com/2022/07/19/carbon-programming-language-google-cpp/
---
> Added Carbon language from Google.

- topics/azd-templates/index.md
---
Since azd is the command-line utility for invoking the Azure Developer CLI, including azd will make things clearer.
---
> Improved description for azd-templates

- collections/programming-languages/index.md
---
- Imba is a production ready language that has been under development for many years.
- Imba has [5,700 stars](https://github.com/imba/imba/stargazers) on GitHub.
- Imba has [522 dependent repositories](https://github.com/imba/imba/network/dependents) on GitHub.
- There are [3,443 .imba files](https://github.com/search?&q=extension%3Aimba) on GitHub.
> Add imba to the list of programming languages

- topics/effector/index.md
---
Link to the main website was changed.
> Fix link to an effector main site

- topics/hacktoberfest/index.md
---
> Small typo was overlooked in PR #3269 before merging
> Fix typo from Hacktoberfest topic

- topics/whatsapp/index.md
---
> Facebook Inc. is now called Meta Platforms Inc.
---
> Update whatsapp topic

- topics/facebook/index.md
---
> Facebook Inc. is now called Meta Platforms Inc.
---
> Update facebook topic

- topics/oai-pmh/index.md
---
> OAI-PMH is standard API since 20 years for digital archives. GitHub contains around 120 repositories tagged with oai-pmh or oai.
---
> Add topic OAI-PMH

- topics-todo.md
- topics/client/index.md
---
The 'client' topic is currently in the 'todo-list.md' so I have created the topic
---
> Create 'client' topic.

- collections/github-pages-examples/index.md
> fix old link

- collections/made-in-indonesia/index.md
> Add awesome repository

- topics-todo.md
- topics/automation/index.md
> Add automation topic

- topics/chaos-engineering/index.md
- topics/sre/index.md
> Add site reliability engineering (SRE) topic

- topics-todo.md
- topics/education/index.md
> Add education topic

- topics/mastodon/index.md
---
Updated the GitHub org name tootsuite -> mastodon
Added related topics
Improved description to reflect current releases of project (removed OStatus reference, added WebFinger)
Updated link to client apps
> Update Mastodon entry

- topics/esp32/index.md
---
> ESP32 is widely used in schools, university, personal projects and many peoples have published their code with ESP32 to GitHub
---
> :pencil2: Add new esp32 topic

- topics-todo.md
- topics/data-analysis/index.md
> Add new data-analysis topic

- topics-todo.md
- topics/tutorial/index.md
> Add new tutorial topic

- topics-todo.md
- topics/test/index.md
> Add new test topic

- collections/made-in-iran/index.md
> َUpdate index.md

- test/topics_test.rb
This avoids some unwanted test failures
> Update to check for either carriage return or new line

- .github/workflows/collections_test.yml
- .github/workflows/topics_test.yml
Add separate test files for topics and collections so that we only run the ones we need
> Separate test files for topics and collections

- topics/advent-of-code/index.md
---
> Advent of Code 2022 as begun and the topic aliases are needed to make link the new year
---
> Add 2022 topic aliases for Advent of Code

- topics/abap/index.md
---
---
Quick follow-up to fix the odd line-breaks:
> Fix line-breaks in ABAP topic

- topics-todo.md
the data topic is already described
> update topics todo list

- topics/motorola-68000/index.md
---
> Motorola 68000 is a microprocessor that has multiple assemblers, compilers, and operating systems. It is used in many personal computers, workstations, and game consoles, including the Apple Macintosh, Atari ST, Commodore Amiga, and the Nintendo Entertainment System.
> This topic is not curated right now and has no explanations
> see index.md
---
> add topic "motorola-68000"

- topics/musicxml/index.md
---
`musicxml` is a standard format for musical notation.
---
> add musicxml

- topics/minecraft-addon/index.md
---
There are several topics which mean the same thing but are not currently given the icon and description.
---
> add aliases for minecraft-addon

- topics/syntax-highlighting/index.md
---
There are 2214 repos with this topic.
---
> Syntax highlighting

- topics/guilded/index.md
---
There are over 58 repositories with this topic, and I can only expect this number to grow with the platform, especially with the recent decision to terminate the API early access program.
---
> Add topic guilded

- topics/adobe-acrobat/index.md
> update adobe acrobat topic

- topics/astrophysics/index.md
---
There are nearly 1,000 [repositories currently tagged with `astrophysics`](https://github.com/topics/astrophysics), including major libraries such as [astropy](https://github.com/astropy/astropy/) and other widely-used code and resources.
---
> Add "astrophysics" topic

- collections/javascript-state-management/index.md
---
> Statemanjs is an excellent state manager for JavaScript applications.
> Add statemanjs

- topics/astronomy/index.md
---
There are over 2,500 [repositories currently tagged with `astronomy`](https://github.com/topics/astronomy), and it is one of the oldest branches of science in existence. This GitHub topic is useful in that it provides a common space for scientists and developers interested in astronomy to browse repositories they might find useful or valuable.
---
> Add "astronomy" topic

- topics/classless/index.md
---
1\) it's helpful to have that little description sidebar of what the "classless" tag means (in this case, relating to CSS) and 2) it would help bind "classless", "classless-css", and "classless-theme" into aliases of each other.
---
> Create topic for classless CSS

- .github/workflows/conflict.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
Add merge queue triggers for actions
> Add action triggers for merge queue

- topics/deta-space/index.md
---
Update `deta-space` url without the `www.` because 1) it looks ugly and 2) it doesnt redirect oops
sry
> Fix `deta-space` url

- topics/grid-computing/index.md
> add topic grid computing

- topics/stem/index.md
> add topic for "STEM"

- topics/citizen-science/index.md
> add citizen science topic

- topics/alternate-reality-game/index.md
- topics/interactive-fiction/index.md
---
> [Making edits to a topic](https://github.com/github/explore/blob/main/docs/API.md#display_name) says "Should use proper noun capitalization."  From looking through existing entries, such as `Package manager` and `Perceptual hashing`, this seems to be "Sentence case".
---
> Display names should be written out, sentence case

- topics/computer-science/index.md
> add topic computer science

- topics/deep-neural-networks/index.md
> add topic deep-neural-networks

- collections/choosing-projects/index.md
This project has been marked read-only by its owner.
- [ X] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [ X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
- [X ] Suggesting edits to an existing topic or collection
---
- [ x] Content (and my changes are in `index.md`)
I propose we remove HospitalRun.
This project has been marked read-only by its owner.
First time contributor, Please let me know if I need to make any corrections. I read the guide and believe I adhered to the standards.
**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested …
> Remove HospitalRun

- collections/made-in-spain/index.md
---
> Pretty popular software developed by a Spanish company (Kaleidos)
---
> Add penpot and taiga to made in Spain

- collections/made-in-india/index.md
This is great tool for quick computation across different areas.  
Quick link to the repo https://github.com/abhimanyu003/sttr
---
This is great tool for quick computation across different areas. 
---
> Add sttr in made-in-india collection

- collections/productivity-tools/index.md
---
> I think clipboard is a really useful tool for development
---
> Add in clipboard

- topics/whisper/index.md
---
> Whisper is a newer product from openAI which will gain a lot of attention in the near future.
> Created "whisper" topic

- collections/front-end-javascript-frameworks/index.md
> Adding nextjs in frontend-javascript-framework collection list

- topics/blockly/index.md
---
> This is a very popular library used by over 250 apps.
---
> Add blockly

- topics/error-propagation/index.md
---
Error(/uncertainty) propagation is a fairly general topic with wide-ranging applications and a growing number of related code projects.
---
> Add error propagation topic

- collections/game-engines/index.md
---
> ## Add `indigo` and `cosplay` to `game-engines`
> I think `indigo` and `cosplay` are good game engines which deserve to be mentioned in the `game-engines` collection.
> - [PurpleKingdomGames/indigo](https://github.com/PurpleKingdomGames/indigo): A game engine for functional programmers
> - [nivanov/cosplay](https://github.com/nivanov/cosplay): CosPlay - 2D ASCII Game Engine for Scala
---
> Add indigo and cosplay to game-engines

- collections/choosing-projects/index.md
> I'm updating the list of How to choose (and contribute to) your first open-source project.
---
---
> Update the choosing-project list

- topics/anime/index.md
---
There's so many anime projects on github but no explaination what anime is that's why i wanted to add the anime topic to `github/explore` so that people can be informed what anime is when they're looking at the topic site
---
> Add Anime topic

- topics/zip/index.md
(blurb from wikipedia via google search)
---
There are 1316 public repositories with the topic `zip`.
---
> add zip topic

- collections/made-in-turkey/index.md
add [trendyol/baklava](https://github.com/Trendyol/baklava) to list
> ### Please confirm this pull request meets the following requirements:
> * [x]  I followed the contributing guidelines: https://github.com/github/explore/blob/main/CONTRIBUTING.md.
> * [x]  I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
> 
> ### Which change are you proposing?
> * [x]  Suggesting edits to an existing topic or collection
> * [ ]  Curating a new topic or collection
> * [ ]  Something that does not neatly fit into the binary options above
> 
> ### Curating a new topic or collection
> * []  I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. …
> Add baklava to Made in Turkey Collection

- collections/css-frameworks/index.md
add [Trendyol/baklava](https://github.com/Trendyol/baklava) to  css frameworks collection
> ### Please confirm this pull request meets the following requirements:
> * [x]  I followed the contributing guidelines: https://github.com/github/explore/blob/main/CONTRIBUTING.md.
> * [x]  I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
> 
> ### Which change are you proposing?
> * [x]  Suggesting edits to an existing topic or collection
> * [ ]  Curating a new topic or collection
> * [ ]  Something that does not neatly fit into the binary options above
> 
> ### Curating a new topic or collection
> * []  I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. …
> add Trendyol/baklava to css frameworks collection

- topics/powershell/index.md
---
> Add Microsoft website where you can find software overview, download and documentation
> Update powershell index

- collections/github-browser-extensions/index.md
---
I have used `hypercrx` 2 years. It's a tool help user know metrics about a repo or a user clearly. I love this extension.
> data: update github-browser-extensions

- collections/github-browser-extensions/index.md
---
> Our CI pipeline told me to 😰 
---
> Update github-browser-extensions due to repo rename

- topics/plaintext-accounting/index.md
---
> The plaintext-accounting community continues to grow with new tools being actively developed, curating the topic will help highlight the 100+ repositories using it.
> add plaintext-accounting topic

- topics/passkeys/index.md
> added initial passkeys file

- test/topics_test.rb
- test/topics_test_helper.rb
- topics/bigquery/index.md
---
The import requires 100 characters or less. I basically copied this test from the display_name test above.
---
> [Tests] Check created_by length

- topics/spacetraders/index.md
Although the tests do not fail, the import of topics into
the website will fail if there is a topic (like this one)
that does not contain a long description as the second yaml
doc after the `---` separator
---
---
> Add longform description to spacetraders topic

- collections/productivity-tools/index.md
---
> Remove duplicated line
---
> Update productivity-tools index.md

- topics/vba/index.md
---
I'm adding related topics to VBA and clarifying the description regarding programs VBA is built into.
> VBA: Add related topics and clarify description

- topics/minecraft-forge/index.md
---
The topic [`forge`](https://github.com/topics/forge) has 1,878 public repositories matching this topic.
I spent a few minutes scrolling this topic, and I didn't see a single repository that wasn't related to Minecraft modding using the Forge loader.
---
> add `forge` alias to `minecraft-forge` topic

- topics/lamp.md
---
> LAMP is a very popular group of software to server operators. Even the Wikimedia projects use it.
---
> Add `lamp` topic

- collections/game-engines/index.md
---
cocos2d/cocos2d-html5 is not maintained anymore, cocos-engine is the next generation game engine of Cocos for cross platform game development including web and native, cocos/cocos-engine also have more stars.
---
> Replacing cocos2d/cocos2d-html5 with cocos/cocos-engine

- CONTRIBUTING.md
Three sentences, two typos. A new record!
> Fix typos in contributing guide

- topics/midi2/index.md
---
MIDI 2.0 specs were recently published and there will be an increasing number of related projects in the future.
---
> Added MIDI 2.0 topic

- topics/physics/index.md
---
> Physics is a fundamental area of research that has an unprecedented impact on the world. As the use of computation within physic increases, it deserves recognition as a value topic to contribute to.
---
> Curate physics topic

- collections/made-in-italy/index.md
---
> I have added apivault.dev to the made-in-italy collection, our website is currently helping thousand of developers around the world, and all the maintainer are italian!
> Add apivault in made-in-italy

- collections/open-source-organizations/index.md
Added Social Income from the GitHub DPG Open Source Community Manager Program
---
Added a open source repo from GitHub's own DPG Open Source Community Manager Program: Social Income (open source for fighting extreme poverty)
> Add Social Income

- collections/cheatsheets/index.md
---
> Currently, the cheatsheets collection includes only cheatsheets for programming languages, I have extended this collection to include cheatsheets for commands too.
---
> cheatsheets: update collection to include cheatsheets for commands too

- topics/flatpak/index.md
---
> This PR links `flathub` and `linux` topic to the current `flatpak` topic as Flatpak is a packaging format for packaging and distributing apps for Linux and Flathub is the defacto remote for publishing Flatpaks.
---
> flatpak/index.md: add related topics

- collections/made-in-brazil/index.md
> add rio term in brazil

- topics/sdl/index.md
---
These tags are much more commonly used, but refer to different versions of the same library.  Trying to capture them all in one place.
> [topics/sdl] Add sdl2, sdl3 aliases

- topics/game-development/index.md
---
"gamedev" has 6,000+ repositories, some 25-35% of "game-development" having 19,000+
> [topics/game-development] Add 'gamedev' as alias

- collections/game-engines/index.md
---
>  I propose adding [LITIENGINE](https://github.com/gurkenlabs/litiengine) to the game-engine collection for making it easier to find for Java Developers. It features a comprehensive Java library for Game Development including a basic game infrastructure, 2D render engine, 2D sound engine, 2D physics engine, support for tile maps in .tmx format, and support for various ways to accept player input. Plus, it’s available through Maven Central for easy integration into your project.
> Adding LITIENGINE to the Game Engines Collection

- collections/learn-to-code/index.md
> Updated collections

- collections/made-in-brazil/index.md
> Add avelino/awesome-go

- topics/kotlin-multiplatform/index.md
---
Added Kotlin Multiplatform, a cross platform development framework from JetBrains.
> Add Kotlin Multiplatform

- topics/cst/index.md
---
Since there's already a topic for [abstract syntax trees](https://github.com/topics/ast), it seems only logical to have that for concrete one's as well.
Since there's already a topic for [abstract syntax trees](https://github.com/topics/ast), it seems only logical to have that for concrete one's as well.
---
> Add topic for "cst"

- topics/ll-parser/index.md
> Add topic "LL parser"

- topics/iso-8601/index.md
---
ISO 8601 is THE standard when it comes to date and time formatting across the world.
---
> Add topic "ISO 8601"

- collections/opensource-testing/index.md
---
Adding VIVIDUS test automation tool to the collection of OpenSource Testing Frameworks & Tools
---
> Add VIVIDUS to OpenSource Testing collection

- collections/clean-code-linters/index.md
---
PMD is a powerful and extensible multilanguage static code analyzer.
---
> Add PMD to Clean Code Linters collection

- collections/clean-code-linters/index.md
---
Spotless can format <antlr | c | c# | c++ | css | flow | graphql | groovy | html | java | javascript | json | jsx | kotlin | less | license headers | markdown | objective-c | protobuf | python | scala | scss | sql | typeScript | vue | yaml | anything> using <gradle | maven | sbt | anything>.
---
> Add Spotless to Clean Code Linters collection

- topics/seo/index.md
---
SEO is crucial to the search engine results page ranking and therefore a central topic for the entirety of the web.
---
> Add topic "SEO"

- collections/choosing-projects/index.md
---
This repo curates beginner-friendly and active open-source repositories for developers. Embedchain is an active open source framework that has a lot of beginner-friendly issues. A developer when working on these issue will get to learn about both AI and open source.
This commit is about following:
Add embedchain. 
Embedchain is an open source framework for software developers who doesn't know AI but want to integrate AI It has a lot of beginner-friendly issues and fixing these issues a developer will end up learning about AI and open source both.
> Add embedchain (beginner friendly AI dev tool)

- collections/clean-code-linters/index.md
---
SpotBugs is a tool for static analysis to look for bugs in Java code.
---
> Add SpotBugs to Clean Code Linters collection

- topics/psr-4/index.md
---
PSRs are a widely used standard for the PHP community.
---
> Add topic "PSR-4"

- collections/react-ui/index.md
---
> Adding [material-tailwind](https://github.com/creativetimofficial/material-tailwind) React UI library in React UI collection.
---
> Adding Material tailwind in React UI

- topics/orm/index.md
---
ORMs are programming language-agnostic and therefore&mdash;especially since the rise of OOP&mdash;used widely across the programming community.
---
> Add topic "ORM"

- topics/i18n/index.md
---
i18n is a topic of international magnitude
---
> Add topic "i18n"

- topics/localization/index.md
---
Make it consistent with #3892
---
> Add related topics, URLs and numeronym alias to topic "l10n"

- topics/continuous-integration/index.md
---
CI is strongly tied to CD within the continuous software development cycle
---
> Add related topics to "CI"

- collections/nextjs-blog-templates/index.md
---
> Adding [nextplate](https://github.com/zeon-studio/nextplate) template in nextjs-blog-templates collections
---
> Adding next plate template

- collections/choosing-projects/index.md
- collections/web-accessibility/index.md
---
I added more beginner-friendly projects to the index.md` file. 
---
> feat: adding beginner-friendly repos

- topics/continuous-delivery/index.md
---
The whole field of CI/CD is getting more and more important, especially due to automation.
---
> Add topic continuous-delivery

- topics/nosql/index.md
> Add aliases and related to noSQL

- collections/static-site-generators/index.md
---
> Adding a [docsify](https://github.com/docsifyjs/docsify) in the static site generator collections list—Docsify is used for generator documentation.
---
> Adding docsifyjs in static site generators

- topics/semantic-web/index.md
---
Semantic web is not just HTML with meaning, it's also about machine readable web contents in general, so there's a broad application of this standard.
---
> Add topic semantic web

- topics/quarto/index.md
---
Links were not displaying properly due to word wrap.
> Rewrap and fix links in Quarto topic

- topics/localization/index.md
---
> There are **10 letters** between l and n in localization, not 18.
> chore: fix a typo

- topics/smoke-tests/index.md
---
Smoke testing is a vast topic, and some guidance to any stumbling upon it would be beneficial.
---
> Add topic smoke-tests

- topics/activitypub/index.md
---
Add some less vague topics to related
---
> Add related to topic "ActivityPub"

- topics/csv/index.md
---
Add RFC and other topics
---
> Add related to topic "csv"

- topics/database/index.md
---
There are many types of databases (see related)
---
> Add related to topic "database"

- topics/nodejs/index.md
---
Add related topics about features, alternatives and hierarchical data to topic
---
> Add related to topic "nodejs"

- topics/deno/index.md
---
Emphasize the relationship with other JavaScript runtime and Deno's features
---
> Add related to topic "deno"

- topics/devops/index.md
---
Add similar topics as well as sub topics
---
> Add related to topic "DevOps"

- topics/f-droid/index.md
---
Add other free app stores
---
> Add related to topic "F-Droid"

- topics/git/index.md
---
Added other git platforms and vcs.
---
> Add related to topic "git"

- topics/sass/index.md
---
Libraries as aliases, features and alternatives as related
---
> Add related and aliases to topic "Sass"

- collections/made-in-brazil/index.md
---
The project I am adding is very relevant in Brazil (and [internationally recognized](https://digitalpublicgoods.net/information-pollution/)). It has an active community and maintainers.
---
> Add project in index.md

- topics/jest/index.md
---
Added other js testing solutions as well as some categories
---
> Add related to topic "Jest"

- topics/monitoring/index.md
---
Observability and alerting are closely tied to monitoring
---
> Add related to topic "monitoring"

- topics/nunjucks/index.md
---
Add alternative templating engines to related topics
---
> Add related to to topic "Nunjucks"

- topics/yaml/index.md
---
Similar config file formats
---
> Add related and created_by to topic "YAML"

- topics/hackathon/index.md
---
The `aliases` key is duplicated—while GitHub's markdown YAML frontmatter parser is not currently bothered, it doesn't mean, it stays that way or others aren't. Plus, it might confuse other contributors who might miss one of the `aliases` at the first glance and might attempt to add supposedly missing `aliases`.
---
> Fix "duplicated mapping key"

- topics/egui/index.md
> Added egui

- topics/clu/index.md
---
CLU was an influential language.  There is not much activity associated with CLU, but It would be nice to associate a topic with the language name.
---
> Add topic "clu"

- topics/kokkos/index.md
---
Fix a typo - avoid PascalCase in the short description of the topic.
> Improve topic "kokkos"

- topics/gitops/index.md
---
Similar to DevOps, AutoDevOps, ChatOps and DevSecOps, also GitOps can be part of a software development workflow.
---
> Add topic "gitops"

- topics/spreadsheet/index.md
---
- [y] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [y] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>
First and foremost an overview page about the different solutions by different vendors. 
---
**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested …
> Add topic "Spreadsheet"

- topics/mediawiki/index.md
---
Wiki platforms as well as features
---
> Add related to topic "MediaWiki"

- topics/climate-change-mitigation/index.md
- topics/fantasy-game/index.md
- topics/hackathon-kit/index.md
- topics/hackathon-organiser/index.md
- topics/league-of-legends/index.md
- topics/meilisearch/index.md
- topics/perceptual-hashing/index.md
- topics/riot-games/index.md
- topics/teamfight-tactics/index.md
- topics/umbraco/index.md
- topics/valorant/index.md
- topics/video/index.md
---
Follow-up to #4016 ([Check errors](https://github.com/github/explore/actions/runs/6701686893/job/18209492242?pr=4016#check-step-7))
| Topic | Related topic | Status |
| ----- | ------------- | :----: |
| [teamfight-tactic](/topics/teamfight-tactic) | [league-of-legends-wild-rift](/topics/league-of-legends-wild-rift) | &check; |
| [hackathon-kit](/topics/hackathon-kit) | [hackathon-organiser](/topics/hackathon-organiser) | Renamed to [hackathon-organizer](/topics/hackathon-organizer)  |
| [meilisearch](/topics/meilisearch) | [entreprise-search](/topics/entreprise-search) | Renamed to [enterprise-search](/topics/enterprise-search) |
| [riot-games](/topics/riot-games) | …
> Remove related topics without repositories from list

- topics/oop/index.md
---
Besides, procedural and functional programming, OOP is an integral paradigm of many programmers' daily work.
---
> Add topic "OOP"

- collections/programming-languages/index.md
---
> The Cython language is recognized by GitHub's language recognition tool, Linguist, but is not listed in the languages actively developed by GitHub.
> add cython language

- collections/learn-to-code/index.md
> Add regexlearn.com

- topics/gmail/index.md
- topics/google-apps-script/index.md
- topics/google-calendar/index.md
- topics/google-chat/index.md
- topics/google-classroom/index.md
- topics/google-cloud/index.md
- topics/google-docs/index.md
- topics/google-drive/index.md
- topics/google-forms/index.md
- topics/google-groups/index.md
- topics/google-keep/index.md
- topics/google-meet/index.md
- topics/google-sheets/index.md
- topics/google-slides/index.md
- topics/google-tasks/index.md
- topics/google-vault/index.md
- topics/google-workspace/index.md
---
It almost looks to me like someone affiliated with Google curated these topics and checked the "conflicts of interest" checkbox anyway or someone copy-pasted straight from Google.
---
> De-sales pitch Google topics

- topics/crud/index.md
---
CRUD is a very central topic, not just for database development but also APIs and such
---
> Add topic "CRUD"

- topics/json-schema/index.md
Add the details of the GitHub repository of the JSON Schema project.
---
---
> Add the details of the JSON Schema repository to "json-schema" topic

- topics/interactive-film/index.md
- topics/visual-novel/index.md
---
Essentially relate them to each other and make them presentable
---
> add related, fix display_name and long description of topics "visual novel" and "interactive film"

- collections/front-end-javascript-frameworks/index.md
I have added Refine.js framework to the list.
---
---
> Add new framework

- topics/api/index.md
---
There's so much more than just REST
---
> Add related to topic "API"

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/conflict.yml
This is perhaps a silly way to do it but the action syntax requires
single quotes and will not accept a backslashed single apostrophe inline.
---
---
> Fix conflict test by removing nested apostrophe, adapt template to match

- collections/made-in-egypt/index.md
---
[Sveltegram](https://sveltegram.a3k.me) is an npm package to facilitate the telegram integration for svelte developers.
---
> Update index.md (made-in-egypt)

- topics/ejs/index.md
---
Other templating engines, primarily for JS
---
> Add aliases, related, created_by. github_url and released to topic "EJS"

- CONTRIBUTING.md
This is adapted from the Community discussions CoC, with a
few tweaks for explore-specific PRs.
> Update CONTRIBUTING to include a section on Gen-AI content

- collections/made-in-france/index.md
Added Quivr
**Quivr is made in France and is sponsored by french companies too ! Go Frenchies**
---
**Quivr is made in France and is sponsored by french companies too ! Go Frenchies**
---
> docs: made-in-france

- collections/static-site-generators/index.md
---
> Adding [nextra](https://nextra.site/) in static site generators collection.
> I added a new nextra library in the static site generators.

- topics/post-quantum-cryptography/index.md
> Active development topic, with hundreds of repositories, critical security importance, and a number of aliases.
> Add post-quantum-cryptography

- topics/xsoar/index.md
---
The XSOAR content repository is fairly popular with 1k+ stars
---
> Curate XSOAR topic

- collections/social-impact/index.md
> add activist.org to projects with social impact

- collections/made-in-brazil/index.md
---
This project provides a REST API to monitor the usage of public money by the members of Sao Paulo City Council. Repo readme and documentation are in Portuguese.
> Add quorum-api to made-in-brazil collection

- topics/declarative-programming/index.md
---
There are 191 public repositories matching this topic.
---
> Curate declarative programming

- CONTRIBUTING.md
- notices.md
> Grammar Correction

- collections/text-editors/index.md
> add helix and kakoune to text editors collection

- collections/made-in-brazil/index.md
---
Add pgModeler to the Made in Brazil collection. The project was created and is maintained by Raphael Araújo e Silva (@rkhaotix) from Palmas, Tocantins.
---
> Add pgModeler

- topics/kokkos/index.md
---
> The website was moved to https://kokkos.org and the old GitHub pages URL https://kokkos.github.io just redirects to it.
> Update URL for Kokkos topic

- collections/game-engines/index.md
---
> Minetest is a voxel game engine providing a powerful modding API allowing for customization as well as game creation.
---
> Add Minetest to the list of game engines

- collections/learn-to-code/index.md
---
> [olexale/flutter_roadmap](https://github.com/olexale/flutter_roadmap) is a popular resource for anyone looking into entering the world of Flutter development.
---
> Add an item to the learn-to-code collection

- topics/sdmx/index.md
---
The SDMX (Statistical Data and Metadata eXchange) topic merits curation due to its pivotal role in data interoperability. As a standardized framework, SDMX facilitates seamless exchange of structured statistical data and metadata across systems. It empowers developers to create robust data pipelines, harmonize disparate datasets, and build analytical tools. By curating SDMX, GitHub fosters collaboration among data professionals, advancing data-driven decision-making and research .
> Add topics/sdmx/index.md for SDMX

- collections/software-in-science/index.md
Added asreview, jupyter-ai, fiftyone, paperlib, and pretzelai
---
- ASReview - very useful for systematic reviews of a lot of papers
- Jupyter AI - connects generative AI with Jupyter notebooks, like a copilot for your notebook
- FiftyOne - enable you to visualize computer vision datasets, including visualizing complex labels, evaluating your models, and much more
- Paperlib - An open-source academic paper management tool
- Pretzel - fast and intuitive data exploration and visualization
- DVC - ML Experiments and Data Management with Git
- git-lfs - Git extension for versioning large files
> Added softwares in science

- collections/made-in-africa/index.md
---
> Add Hexastack/eazychart project to  Made-In-Africa collection
>  Add Hexastack/eazychart project to made-in-africa collection

- collections/productivity-tools/index.md
---
- ConEmu - Windows console emulator with tabs
- Wave Terminal - open-source AI-native terminal
- Termux - terminal emulator app for Android
- Zed - high-performance, multiplayer code editor
- Lapce - powerful Code Editor written in Rust
- NVTOP - top like command for monitoring GPUs
- Rclone - rsync for cloud storage
- tldr - collaborative cheatsheets for console commands
- aria2 - multi-protocol, cross platform CLI download utility
- Bash-it - community Bash commands and scripts
- DVC - ML Experiments and Data Management with Git
- Starship - cross-shell, feature rich prompt made in rust
- Tilix - tiling terminal emulator for Linux using GTK+ 3
- mu-repo - help in dealing with multiple git repositories
- thefuck - …
> Added some productivity tools

- collections/made-in-brazil/index.md
---
- al-folio - um template bem bonito, responsivo, feito para acadêmicos
- multi-language-al-folio - uma versão do template acima com suporte para várias línguas
- diciotech - dicionário online sobre termos da tecnologia
> Added more code made in brazil

- collections/tools-for-open-source/index.md
---
- GitHub Readme Stats - dynamically generated stats for your GitHub readmes
- Markdown Badges - badges for your personal developer branding, profile, and projects
- Badges 4 README - more badges for your README.md
- GitHub Corners - beautiful Fork me on GitHub corner for your site
- GitHub Stats - visualizations of GitHub user and repository statistics
- GitHub Profile Summary Cards - generate your GitHub summary card for profile README
- GitHub Profile Trophy - dynamically generated GitHub Stat Trophies
- GitHub Readme Streak Stats - show off your contribution streak
- GitHub Readme Activity Graph - dynamically generated activity graph
- Star History - hand-drawn-style star history graph of GitHub repos
- GitHub Activity …
> Added lots of tools for Open Source

- collections/design-essentials/index.md
---
- Bootstrap Icons - open source SVG icon library for Bootstrap
- heroicons - free MIT-licensed high-quality SVG icons
- flag-icons - curated collection of all country flags in SVG and CSS
- tabler-icons - free MIT-licensed high-quality SVG icons
- daisyUI - free and open-source Tailwind CSS component library
- Responsively App - modified browser that helps in responsive web development
> Added more icons and web components

- collections/made-in-rwanda/index.md
---
I have added some missing and useful open-source projects that are made in Rwanda.
The following repositories are added:
- [Next13-progressbar](https://github.com/ndungtse/next13-progressbar) : A simple Next.js progressbar component using NProgress with support of next.js >=13 app dir.
- [gcommit](https://github.com/veritem/gcommit): conventional commits utility cli
- [json-base](https://github.com/regisrex/json-base): 📦 a simple odm with cli , for json file-as-bd
- [string-hunt](https://github.com/regisrex/string-hunt): 📦 recursive text searching algo. for small scale data
- [auto-push](https://github.com/IVainqueur/auto-push): A tool to automatically push at a regular interval while you write your code
- …
> Update made-in-rwanda collection.

- topics/extension/index.md
---
I propose a new "Extensions" topic due to their key role in augmenting software functionality and personalization. A dedicated GitHub topic will streamline access to extension-related projects, enhance community engagement, and boost innovation across multiple domains.
---
> add topic: extension

- collections/made-in-brazil/index.md
---
Repository with a list of tech events that occur in Brazil.
> Added repo with list of tech events in Brazil

- collections/made-in-algeria/index.md
> Add repositories to made-in-algeria

- collections/productivity-tools/index.md
> Added logdy to productivity tools

- topics/software-engineering/index.md
---
I propose the creation of a 'Software Engineering' topic to emphasize its structured approach to developing software. This topic will serve as a comprehensive resource for those interested in the methodologies and principles of software engineering, fostering a deeper understanding and enhancing best practices among developers on GitHub.
---
> added: software engineering topic

- topics/programming/index.md
---
I propose creating a new topic for 'Programming' due to its foundational role in the development of software and technologies. A dedicated topic on GitHub will serve as a centralized resource for developers to share, discover, and discuss programming tools, projects, and techniques, enhancing collaboration and learning within the global programming community.
---
> added topic: programming

- topics/interview/index.md
---
I propose the 'Interview' topic to provide a comprehensive resource for job seekers and hiring professionals on GitHub. This topic will cover strategies for preparing and succeeding in various types of interviews, enhancing candidates' abilities to present themselves effectively and navigate the hiring process confidently.
---
> added topic: interview

- topics/generator/index.md
---
I propose adding the 'Generator' topic to explore the diverse types and uses of generators, from conventional fuel-based to renewable energy sources. This topic will serve as a comprehensive guide for understanding how generators work, their applications, and their importance in energy production and emergency power systems. It aims to facilitate knowledge sharing and technical discussion among engineers, technicians, and enthusiasts interested in energy sustainability and infrastructure resilience.
---
**Please note: we will close your PR without comment if …
> added topic: generator

- topics/desktop/index.md
---
I propose creating a 'Desktop' topic to cover the wide range of software applications and technologies specific to personal computers. This topic will serve as a centralized resource for developers and users to share insights, innovations, and discussions about desktop environments, applications, and user interface design. It aims to enhance understanding and collaboration in the development of desktop computing solutions.
---
> added topic: desktop

- topics/image/index.md
---
I propose creating an 'Image' topic to centralize resources and discussions about the creation, editing, and use of images across various media. This topic will provide a platform for professionals and enthusiasts in photography, graphic design, and digital arts to share techniques, tools, and innovations, enhancing the community's understanding and capabilities in visual media.
---
> added topic: image

- topics/project/index.md
---
I propose creating a 'Project' topic to serve as a comprehensive resource for exploring project management techniques and methodologies. This topic will facilitate discussions on best practices, tools, and challenges in managing projects across different industries, helping professionals enhance their skills and successfully deliver project goals.
---
> added topic: project

- topics/network/index.md
---
I propose creating a 'Network' topic to consolidate knowledge and discussions about computer networking. This topic will serve as a central hub for sharing insights on network architecture, security, and emerging technologies, helping professionals and enthusiasts enhance their understanding and skills in this essential and rapidly evolving field.
---
> added topic: network

- topics/software/index.md
---
I propose creating a 'Software' topic to provide a comprehensive resource for understanding different types of software and their applications. This topic will facilitate discussions on software creation, usage, and impact, helping developers and users enhance their knowledge and skills in utilizing software effectively.
---
> added topic: software

- topics/development/index.md
---
I propose creating a 'Development' topic to provide a comprehensive resource on the process of creating and maintaining software applications. This topic will facilitate discussions on best practices, methodologies, and tools, helping developers and project managers enhance their skills and deliver effective software solutions.
---
> added topic: development

- topics/barcode/index.md
---
I propose creating a 'Barcode' topic to provide a comprehensive resource on the use of barcodes for data representation and automation. This topic will facilitate discussions on the different types of barcodes, their applications, and the technologies used for barcode generation and scanning, helping businesses and developers leverage barcodes for efficient data management and tracking.
---
> added topic: barcode

- topics/code/index.md
---
I propose creating a 'Code' topic to provide a central resource for understanding and discussing the writing and maintenance of source code. This topic will help developers share best practices, tools, and insights on various programming languages and coding techniques, fostering a community focused on high-quality and efficient software development.
---
> added topic: code

- topics/simulation/index.md
---
I propose creating a 'Simulation' topic to provide a comprehensive resource on the principles and applications of creating virtual models to study system behavior. This topic will facilitate discussions on various simulation methodologies, tools, and best practices, helping researchers, engineers, and practitioners leverage simulations for testing, training, and prediction purposes.
---
> added topic: simulation

- topics/qrcode/index.md
---
I propose creating a 'QR Code' topic to provide a comprehensive resource on the use and technology of Quick Response Codes. This topic will facilitate discussions on how QR Codes are generated, their applications in various industries, and the best practices for utilizing them effectively, helping businesses and developers leverage this technology for efficient data management and interaction.
---
> added topic: qrcode

- topics/hacking/index.md
---
I propose creating a 'Hacking' topic to provide a comprehensive resource on the practices and implications of hacking. This topic will facilitate discussions on ethical hacking, cybersecurity measures, and the tools and techniques used in hacking, helping individuals and organizations understand the risks and defenses related to unauthorized data access.
---
> added topic: hacking

- topics/cybersecurity/index.md
---
I propose creating a 'Cybersecurity' topic to provide a comprehensive resource on protecting systems, networks, and data from cyber threats. This topic will facilitate discussions on best practices, tools, and strategies for safeguarding information, helping professionals stay informed about the latest trends and threats in the cybersecurity landscape.
---
> added topic: cybersecurity

- topics/exploit/index.md
---
I propose creating an 'Exploit' topic to provide a detailed resource on the methods and techniques used to take advantage of security vulnerabilities. This topic will help cybersecurity professionals understand different types of exploits, their impact, and the best practices for detecting and mitigating them, thereby enhancing the overall security posture.
---
> added topic: exploit

- topics/todo/index.md
---
I propose creating a 'To-Do' topic to provide a comprehensive resource on managing tasks and organizing activities using to-do lists. This topic will help individuals and teams learn about different to-do list formats, popular applications, and best practices for effective task management, enhancing their productivity and organization.
---
> added topic: todo

- collections/static-site-generators/index.md
---
> Publish is a popular static site generator in Swift.
---
> Added JohnSundell/Publish to the collection of static-site-generators

- topics/eeg/index.md
---
EEG is a popular topic that is not yet curated as a list, even though there are many repositories on GitHub on the topic.
> Add EEG as new topic

- topics/visionos/index.md
---
> This topic should be added because the all of Apple's operating systems are also existing topics (except iPadOS since it's a variation of iOS as Apple doesn't explicitly separate iOS and iPadOS)
---
> Create index.md for visionOS

- topics/whistleblowing/index.md
---
I consider this section should be curated in order to highlight the research on the matter performed by human rights defenders and activists in developing and promoting whistleblowing technologies like @freedomofpress and @globaleaks, and many others
---
> Add topic: whistleblowing

- collections/made-in-bangladesh/index.md
- [*] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [*] I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.
- [*] Suggesting edits to an existing topic or collection
---
- [*] Content (and my changes are in `index.md`)
- [*] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [*] All required fields in my `index.md` conform to …
> add bangladesh open source projects and helpful links collection

- docs/API.md
- topics/instrumentation/index.md
---
> Instrumentation is an important technique in computer science and should have a dedicated topic.
---
> create topic: instrumentation

- collections/green-software/index.md
> Create green-software collection

- collections/clean-code-linters/index.md
---
> Added nicklockwood/SwiftFormat to clean-code-linters collection
> Added nicklockwood/SwiftFormat

- topics/zig/index.md
---
This adds precision to the release date and remove an unnecessary trailing slash.
---
This is a minor change that also attempts to kick whatever CI is needed to update [this topic page](https://github.com/topics/zig).
---
> Update Zig release date

- topics/confidential-computing/index.md
---
The confidential computing topic on GitHub still seems rather small but outside of GitHub, the topic is gathering attraction:
- All hardware manufacturers have some product in their portfolio that has confidential computing
- All large and a growing amount of other smaller cloud vendors offer confidential computing services or resources
- Reports like this one from the Linux Foundation are coming out: https://www.linuxfoundation.org/research/confidential-computing-use-case-study and more and more use cases are being developed
Hopefully that convinces you :). The short description is taken from the first Wikipedia sentence, the remainder of the description from the Linux Foundation's Confidential Computing Consortium (CCC). As website I also linked the CCC as it is currently supported …
> Adding confidential computing topic

- topics/vscode-extension/index.md
---
This appends the other alias for vscode as a related topic.
---
> Update VS Code Extension

- topics/fair-source/index.md
> Add Fair Source topic

- topics/redux/index.md
---
redux has moved to it's own org
> Update redux github_url

- collections/text-editors/index.md
---
Added Kate text editor, a 20+ years old editor developed by the KDE community.
---
> Add kate text editor

- collections/game-engines/index.md
---
It's a well known game engine with its own community and a lot of [assets and extensions](https://github.com/topics/defold) on Github.
---
> Add `defold/defold` to the `game-engines` collection

- collections/made-in-india/index.md
Nammayatri is an Open and Driver Centric Mobility Platform.
---
> More people should get to know about Nammayatri, I think it is an interesting project.
---
> Add nammayatri

- topics/dotfiles/index.md
---
Fixed a typo in the dotfiles topic description; where it said "ususually", it has been replaced by "usually".
---
> Fixed typo

- topics/configuration/index.md
---
* The `config` alias resolves one of the most popular un-curated topics
* Lower case is the appropriate capitalization because "configuration" is not a proper noun
* Elaboration in the description makes it more understandable
---
> Update configuration descriptions, capitalization, alias

- collections/made-in-brazil/index.md
---
Added repo with Front-End work positions. Saw that it already had one for back-end, so this one was missing.
> Adicionado frontendbr/vagas

- collections/virtual-machines/index.md
---
> Virtual Machines are useful resources to experiment with software and are quite popular. It would be helpful to have a curated list of projects that can be used for these purposes.
---
> Add new collection: Virtual Machines

- .github/workflows/jekyll_build.yml
- topics/whistleblowing/index.md
---
Add `id-token: write` permission to deploy step
[Error from last deploy try](https://github.com/github/explore/actions/runs/11299377372/job/31430324404#step:2:21)
---
> fix: permissions for deploy

- topics/Verilog/index.md
- topics/verilog/index.md
> Adding Verilog to the topics

- topics/recon/index.md
---
- [] Content (and my changes are in `index.md`)
> Recon is an important part of security testing. There are 856 public repositories as of today under this topic.
> Added description to the topic.
---
> Added Recon to Topics

- .github/workflows/collections-renames.yml
- Gemfile
- Gemfile.lock
---
collections-renames.yml workflow runs have been failing since 10/20/2024.  This will fix that.
---
> fix: update collections-renames.yml to use the correct action permissions

- collections/fantasy-consoles/index.md
---
[WASM-4](https://wasm4.org/) is a fantasy console that I have used in the past that I believe fits among the existing entries.
---
> Add the WASM-4 repository to the fantasy consoles collection

- topics/cryptography/index.md
> removed typo

- collections/made-in-france/index.md
> Added axone-protocol org to made-in-france

- collections/green-software/index.md
was renamed in https://github.com/github/explore/pull/4550 incorrectly
---
---
> fix: badly rename repo

- collections/pixel-art-tools/index.md
> fix: removed repo causes collection to fail on import in biztools

- collections/playdate-rust/index.md
formatting it to match other collections.
---
---
> chore: trying to fix playdate-rust for import into biztools

- topics/pdo/index.md
---
PDO has 1,066 repositories
---
> Create topic "PDO"

- topics/oidc/index.md
---
Together, `oidc` and `openid-connect` have more than 2k repositories
---
> Create topic "OIDC"

- topics/datetime/index.md
---
datetime has over 2,000 repositories
---
> Create topic "DateTime"

- collections/static-site-generators/index.md
---
> I added the [fuma docs](https://github.com/fuma-nama/fumadocs) in `collections/static-site-generators`. Fumadocs is a robust and beautiful documentation framework featuring a complete toolchain. It is designed for flexibility, performance, and Next.js.
---
> Adding fuma docs in collection

- collections/programming-languages/index.md
> Add 5 programming languages

- .github/workflows/collections-renames.yml
- .github/workflows/jekyll_build.yml
- .github/workflows/lint.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
Fixes security notifications
---
---
> ci: change immutable workflows to semver

- Gemfile.lock
Updating to try and solve the linting action issues as shown here: https://github.com/github/explore/actions/runs/13032194764/job/36353819322?pr=4606
ran:
```sh
bundle lock --add-platform ruby
bundle lock --add-platform x86_64-linux
bundle lock --add-platform arm64-darwin
bundle lock --add-platform x86_64-darwin
```
> Update package platforms

- topics/transgender/index.md
---
There are many repos about transgender topics on GitHub
---
> Add transgender topic

- topics/cellular-automaton/index.md
---
> Unify the plural `cellular-automata` (1,380 repos) with the singular `cellular-automaton` (487 repos) to simplify searching and tagging.
---
> Add cellular-automaton topic

- collections/game-engines/index.md
OpenFL is cross platform development engine  supporting compilation to iOS , Android , HTML5 and other platforms
- [ X] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [ X] I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.
- [ X] Suggesting edits to an existing topic or collection
---
- [ X] Content (and my changes are in `index.md`)
OpenFL started as a replacement for the popular Flash API, but following the open source path.
Now it supports many platforms like HTML5, Android, iOS.
> Please replace this line with an explanation of why you think this topic or collection …
> Add OpenFL game engine

- collections/dil-dil-pakistan/index.md
> Added Streetwriters to dil-dil-pakistan

- topics/noaa-nsap/index.md
---
> The National Stock Assessment Program within NOAA Fisheries produces multiple R packages and many other software tools. The topic is of interest to many scientists and the topic will help viewers of the topic know what noaa-nsap stands for because although NOAA is a well-known acronym, NSAP is not as well known.
---
> feat(noaa-nsap): Adds noaa-nsap topic

- collections/made-in-colombia/index.md
- collections/voxel-editors/index.md
---
> This project is being used by many developers and users in applications in play store, it's usefull for many developers.
---
> Update made in colombia index.md

- collections/dil-dil-pakistan/index.md
> Added Notesnook to dil-dil-pakistan

- collections/pixel-art-tools/index.md
---
I want to share this tool with more people.
> Pixed - new pixelart tool

- topics/robomaster/index.md
---
> The reason why I think this topic or collection should be curated is that it is an important and well-known robot competition in China.  It can improve the embedded development, computer vision or other professional skills of the participants.  It has received support from many Chinese official media, and many top Chinese universities have participated.  Most of the students who have participated have a high evaluation of it, and there are already many related repositories on GitHub.
> Add topic: RoboMaster

- topics/authorization/index.md
The highly related topic of "authentication" exists, so "authorization" should exist as well.
> add topic: authorization

- collections/text-editors/index.md
Add Pulsar, a hackable and community-led text-editor to the list of open source editors.
---
> Pulsar is now a popular fork of Atom and as such its only righ tthat it be included in the list of open source editors.
---
> Add pulsar in open source editors

- collections/made-in-russia/index.md
---
Corporate Network Security Recommendations That Have Become Popular with Consumers in Russia.
Just add one of most popular repo from Russia.
> Add segmentation cheat sheet with 3.3k stars

- CONTRIBUTING.md
Relates to https://github.com/github/explore/pull/4780
---
---
> chore: simplify contributing to match previous self promotion changes

- topics/sport/index.md
- topics/sports-game/index.md
- topics/sports/index.md
---
The [`sports`](https://github.com/topics/sports) topic contains **1,672** public repositories as of today. It is a large field of action and many softwares are created to enhance the sports experiences. Let's create a topic for this theme.
This PR relies on PR #4813 which removes the irrelevant `sports` alias of an existing topic.
> Add `Sports` topic

- collections/devops-tools/index.md
- collections/software-development-tools/index.md
---
Adding an open source alternative (Apache-2) to other open source CI/CD platforms.
---
> add semaphoreio/semaphore open source CI/CD

- collections/demo-sources/index.md
> Add jumalauta/jml-engine-demos to demo sources
