- test/topics_test.rb
These shouldn't be capitalised to GitHub.com so let's just strip them from the test strings altogether.
As seen in #49 CC @shroudedcode and https://github.com/github/explore/pull/27 CC @nayafia @kentcdodds
> topics_test: don't complain about github.com URLs.

- test/topics_test.rb
- topics/amphp/index.md
- topics/sitecore/index.md
This branch adds some commas to suit our styleguide and also checks the 'created_by' field for Oxford commas.
> Add a couple missing Oxford commas

- test/test_helper.rb
- test/topics_test.rb
- topics/github-api/index.md
This adds a couple tests to ensure the "github_url" and "wikipedia_url" fields look somewhat correct. They must be parseable as URIs and have an expected host.
> Test for valid GitHub and Wikipedia URLs

- topics/react/index.md
https://reactjs.org/ is now the new homepage.
I am:
[On September 29](https://twitter.com/reactjs/status/913797391307833344) the React homepage got relocated to https://reactjs.org/
> Update React Homepage URL

- test/topics_test.rb
- topics/perl/index.md
This branch:
- Improves our tests so that if you specify a logo using an incorrect file name, it will fail. For example, the perl topic said `logo: perl5.png`, but the file in the perl/ directory was actually perl.png.
- Fixes the perl topic to use the right file name for its logo.
> Fix incorrect perl logo file name

- docs/API.md
- topics/graphql/index.md
- topics/mahapps/index.md
- topics/material-design/index.md
This makes "metro" a related topic to "mahapps" instead of an alias. That way the mahapps curated content will not show on /topics/metro, as not every repository using the metro topic is related to mahapps.
This also adds "wpf" as a related topic to "mahapps".
> Change aliases, related topics on mahapps topic

- topics/bash/index.md
- topics/c/index.md
- topics/clojure/index.md
- topics/csharp/index.md
- topics/elixir/index.md
- topics/go/index.md
- topics/julia/index.md
- topics/laravel/index.md
- topics/perl/index.md
- topics/php/index.md
- topics/python/index.md
- topics/r/index.md
- topics/rails/index.md
- topics/react-native/index.md
- topics/react/index.md
- topics/redux/index.md
- topics/rest-api/index.md
- topics/ruby/index.md
- topics/rust/index.md
- topics/shell/index.md
- topics/swift/index.md
- topics/typescript/index.md
I am:
For the react changes: if someone lands on /topics/react, they might not know react-native is a thing. Oppositely, if they land on /topics/react-native, it'd be good to link back to react so they can find out about the base framework.
I also added related topics to connect languages, and tie topics for programming languages back to the general 'languages' topic. I think this will let users branch out to discover new languages.
> Add more related topics

- topics/amphp/index.md
I am:
Please explain why these changes are necessary: Initially I put the first stable release date there instead of the first release.
> Use Amp's first release instead of first stable release

- docs/API.md
- test/topics_test.rb
- topics/wagtail/index.md
This adds a new test to ensure we don't have commas after month names in the 'released' field. It also removes such a comma from the 'wagtail' topic.
> Add test to find bad comma position in 'released' field

- topics/nim/index.md
- topics/spacevim/index.md
This makes a couple small fixes to two existing topics:
- A couple grammar fixes for nim. /cc @data-man 
- Fixes unintentional wrapping in the spacevim body from newlines being rendered as `<br>` tags. See before:
/cc @wsdjeg
> Fix a couple things with spacevim, nim topics

- topics/flask/index.md
This is just a small typo in the name of https://github.com/pallets/werkzeug
> Typo in index.md

- test/topics_test.rb
This is a fix for a failing test seen in https://github.com/github/explore/pull/147. We normally want numbers less than ten to be written out, but "Raspberry Pi 3" is the correct name, so the test shouldn't complain it's not "Raspberry Pi Three."
> Add test exception for 'Raspberry Pi 3'

- topics/raspberry-pi/index.md
The Raspberry Pi is a single-board computer, not a microcontroller.
Additionally reworded the sentences for better reading, and added that there are difference variations of the Pi available.
I am:
Incorrect information throughout.
> Remove Micro-controller references from RPi

- topics/es6/index.md
I am:
ECMAScript is the canonical capitalisation. It should be used consistently.
> Consistently capitalise ECMAScript

- topics/pwa/index.md
I am:
As someone who has been involved with the creation of progressive web apps since day one (I wrote the O'Reilly book [Building Progressive Web Apps](https://pwabook.com)), I think the current topic needs two changes:
- Remove the `created_by` field which only listed two people as the creators of progressive web apps. While Francis and Alex were immensely influential for the creation of progressive web apps and service workers in particular, and while I personally adore and have been floored by the depth of Alex's intelligence and vision in every single interaction I ever had with him (I never had a chance to meet Francis), I think it …
> Updated progressive web apps topic

- collections/social-impact/index.md
- collections/web-games/index.md
Two updates here:
* [julianguyen/ifme](http://github.com/julianguyen/ifme) has moved to an organization at [ifmeorg/ifme](http://github.com/ifmeorg/ifme)
* [Q43/0hh1](http://github.com/Q43/0hh1) seems to have been deleted
> Update renamed and deleted repos

- Gemfile
- Gemfile.lock
This isn't necessary unless we have known breakages. `Gemfile.lock` will take care of pinning the versions for us.
> Don't pin gem versions

- collections/pixel-art-tools/index.md
The image file is there but it's not in the YAML.
> collections/pixel-art-tools: add missing image.

- test/collections_test.rb
- test/collections_test_helper.rb
If a user, organization, or repository has been renamed, we should get a test failure so we can rename the item.
> Add test for collection item renames

- collections/programming-languages/index.md
- test/collections_test.rb
- test/collections_test_helper.rb
We're only display 40 now (was 20) so enforce this to avoid confusion.
> Enforce the maximum of 40 items in a collection.

- collections/tools-for-open-source/index.md
- skywinder/github-changelog-generator has been renamed to github-changelog-generator/github-changelog-generator
- facebook/mention-bot has been renamed to facebookarchive/mention-bot (so remove it)
> collections/tools-for-open-source: handle renames

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/collection.md
- .github/PULL_REQUEST_TEMPLATE/topic.md
Collections and topics are better if collated by fans rather than the authors of software.
See e.g. #233, #230, #229 (and others).
> Clarify self-promotion requirements

- .travis.yml
This avoids duplicating builds for PRs not from forks.
> travis.yml: only build master branch.

- collections/github-browser-extensions/index.md
It was renamed to a repo that was already here so just remove it.
> collections/github-browser-extensions: fix renamed repo.

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/collection.md
- .github/PULL_REQUEST_TEMPLATE/topic.md
When the PR templates use strings of asterisks, they don't use a standard number. That in itself wouldn't have caught my eye… but the Preview view of the PR message in a new PR did:
<kbd>
</kbd>
When I sat down to delete that extra asterisk, I realized there was no standard number. With this PR, the extra asterisk is gone and the length of asterisk strings is standardized
> pr templates: standardize asterisk counts

- topics/thelounge/index.md
I am:
***********EDITING AN EXISTING TOPIC OR COLLECTION************
The URL of the repository has changed recently. Even though the redirect is in effect, https://github.com/thelounge/thelounge is now the canonical location.
> Fix repo URL of The Lounge

- collections/machine-learning/index.md
Add the largest open (and free) machine learning course (articles, Jupyter notebooks, assignments, projects, tutorials, Kaggle Inclass competitions and active community OpenDataScience). Here is a publication on Medium https://medium.com/open-machine-learning-course
- \[x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
I am:
- \[x] Suggesting edits to an existing topic or collection
- \[x] Content (and my changes are in `index.md`)
I'm proposing to include a very good free ML course. 
**Please note: we will close your PR without comment if you do not check the …
> Adding mlcourse_open to ML index.md

- collections/github-browser-extensions/index.md
The [muan/dashboard](https://github.com/muan/dashboard) repository has moved to [muan/github-dashboard](https://github.com/muan/github-dashboard).
> Update name of moved repo

- topics/babel/index.md
I was just looking at a repository that had the babel-preset topic. When I clicked the topic, I noticed the babel-preset topic page has no information about what Babel is. Listing babel-preset as a related topic of babel will change this.
I did a search for "babel" and added the most used babel-related topics to the babel topic index.md to encourage further use and awareness. https://github.com/search?q=babel&type=Topics
> Add an alias and some related topics to babel

- collections/software-development-tools/index.md
> collections/software-development-tools: redirect better_errors.

- collections/social-impact/index.md
This has moved to a get-alex organisation.
> collections/social-impact: redirect alex.

- collections/programming-languages/index.md
Looks like this repo is no longer available. I couldn't find where it
moved to since the entire https://github.com/loli-foundation
organization is gone, so deleting.
> Remove loli language

- topics/rust/index.md
Rust project [updated its website](https://blog.rust-lang.org/2018/11/29/a-new-look-for-rust-lang-org.html) and https://www.rust-lang.org/en-US/ is currently 404. Update to https://www.rust-lang.org/.
> Update Rust URL

- collections/choosing-projects/index.md
- collections/github-browser-extensions/index.md
Builds are broken 😒: 
>   1) Failure:
collections::choosing-projects collection#test_0007_fails if a user, organization, or repository has been renamed [/home/travis/build/github/explore/test/collections_test.rb:90]:
Expected ["choosing-projects: pybee/batavia has been renamed to beeware/batavia"] to be empty.
>   2) Failure:
collections::github-browser-extensions collection#test_0007_fails if a user, organization, or repository has been renamed [/home/travis/build/github/explore/test/collections_test.rb:90]:
Expected ["github-browser-extensions: rgehan/octolenses-browser-extension has been renamed to rgehan/octolenses"] to be empty.
https://travis-ci.org/github/explore/builds/514139240?utm_source=github_status&utm_medium=notification
> Rename moved repositories

- collections/front-end-javascript-frameworks/index.md
> Svelte has just released its v3 which presents revolutionary concepts in the front-end component healm. I'm a dev who uses it since v2 and I think it's time to add Svelte to this list since it gathered quite a popularity over the last 2 years.
> Adding Svelte in front-end frameworks list

- topics/ruby/index.md
To say that Ruby is "integrated with" Ruby is inaccurate. The relationship between Rails and Ruby is one-way: Rails is written in Ruby and enables one to write programs in Ruby. Ruby functions completely independently of Rails.
While creating applications with Rails is a very popular use of Ruby (perhaps one of the _most_ popular), this popularity can cause confusion for new developers. It can be unclear if methods, data structures, etc. are part of the Rails framework or part of the Ruby language itself. Hopefully this change clarifies this a bit better.
I welcome further changes to my wording to make this message sound even more natural.
> Reword Rails's relationship to Ruby for accuracy

- .rubocop.yml
- Gemfile
> Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.
> Start using `rubocop-performance` to fix deprecation warning

- collections/ai-model-zoos/index.md
- collections/open-journalism/index.md
- collections/open-source-organizations/index.md
Fixing a few repos that have moved or been removed.
```
1) Failure:
collections::open-source-organizations collection#test_0005_fails if a repository does not exist or is private [/home/travis/build/github/explore/test/collections_test.rb:56]:
Expected ["open-source-organizations: baidu/baidu.github.io does not exist or is private"] to be empty.
2) Failure:
collections::open-journalism collection#test_0007_fails if a user, organization, or repository has been renamed [/home/travis/build/github/explore/test/collections_test.rb:90]:
Expected ["open-journalism: TimeMagazine/babynames has been renamed to TimeMagazineLabs/babynames"] to be empty.
3) Failure:
collections::ai-model-zoos collection#test_0007_fails if a user, organization, or repository has been renamed …
```
> Update baidu, time, and deeplearning4

- collections/pixel-art-tools/index.md
This commit:
- Removes the https://github.com/ from all of the items
Why?
- This is no longer needed
> Use new repo syntax

- collections/static-site-generators/index.md
I think Hakyll is a popular enough static site generator that it would fit nicely into this list. It's very pleasant to work with, especially if you're already working in the Haskell community :).
> Add Hakyll to static site generators

- collections/github-browser-extensions/index.md
> Simple and useful extension that adds more visibility to the PR list by adding the avatars of the creators
> github-browser-extensions: Add github-show-avatars

- topics/home-assistant/index.md
> A lot of repos use `homeassistant`. This adds an alias for `home-assistant` as `homeassistant`.
> Add home assistant alias without dash

- collections/open-source-organizations/index.md
This PR adds Stripe GH page, `stripe/stripe.github.io`, to the collection named **Open Source Organizations**. I consider it was missing on the organizations listed there, and they have contributed to OSS for a while now.
> Include Stripe GH Page to OSS Orgs collection

- CODEOWNERS
This PR proposes that we add @mvkaran, a member of our DevRel team and the original curator of the `made-in-india` collection, as an official CODEOWNER of that collection
First, he has generously offered! Also, as someone much more plugged into the Indian developer community than any of the current CODEOWNERS are, he is much more qualified to review submissions to this topic.
Perhaps, if DevRel agrees, we could do a bit more of this. @github/communities-heart-reviewers could remain owners in a "if this crashes we can jump in" way, but perhaps a cohort of DevRel could actually work with the community to maintain the content of this repo. Interested to hear others' thoughts! 
cc/ @martinwoodward, too =]
> Add @mvkaran as CODEOWNER for made-in-india

- collections/choosing-projects/index.md
> I'm suggesting removing ```beeware/batavia``` from the "How to choose (and contribute to) your first open source project" page because it has been archived and is now read-only.
> removed archived repository from "Choosing Projects" page

- topics/react-native/index.md
---
---
Currently the URL used in the React Native topic leads to unsecured and unofficial website.
This PR updates the URL to point to the official React Native website located at:
* https://reactnative.dev/
And the source code is available at:
* https://github.com/facebook/react-native-website
I have also updated the Wikipedia link, since React Native have it's own page for a some time:
* https://en.wikipedia.org/wiki/React_Native
---
> use correct URL for React Native website

- collections/social-impact/index.md
- collections/software-defined-radio/index.md
This combined with https://github.com/github/explore/pull/2322 should get CI green again
> Remove Greenstand/Development-Overview because it's private

- collections/made-in-cuba/index.md
Causing to CI to fail because https://api.github.com/users/stepperUnipolar returns a 403 - possibly a user rename?
> Remove stepperUnipolar

- collections/text-editors/index.md
Lite XL is a text editor which improves on top of Lite, an editor already in this collection. I suggest adding it alongside Lite.
> Add Lite XL editor

- collections/game-engines/index.md
Updated GarageGames game engine listings to their new repos, the current repos listed are no longer receiving updates.
GarageGames have moved their game engines to new repos, the current game engine collection on the explore page still displays the old repos however. In this pull request, the index.md has been edited to replace the old GarageGame engine repos with their new and updated versions. The README in the Old Torque2D Engine states that all Torque Engines are moving repos and organizations.(https://github.com/GarageGames/Torque2D/blob/master/README.md), the wiki for Torque2D states this as well. However this is not mentioned in the Old Torque3D …
> Update index.md for Game Engines Collection

- topics/ruby/index.md
> I removed the /en/ at the end of the URL to allow people from other nationalities to be redirected to a page suitable to them.
> Remove the /en/ to allow redirects in Ruby's topic

- test/topics_test_helper.rb
- topics/assembly/index.md
- topics/calculate-pi/index.md
- topics/elm/index.md
- topics/finite-element-method/index.md
- topics/frontend/index.md
- topics/hackathon-kit/index.md
- topics/hackathon-organiser/index.md
- topics/hackathon/index.md
- topics/obofoundry/index.md
- topics/terminal/index.md
- topics/ui-design/index.md
When I went to import recently updated topics, I noticed that the `command-line-interface` topic wasn't importing. After some digging, I noticed that both `command-line-interface` and `terminal` shared the `command-line` alias, which I suspect was preventing the import from succeeding.
I updated our test helpers to properly parse aliases and related topics, and as part of that, I found that there were many aliases and related topics that were duplicates. Most of these were duplicating the name of the topic itself, while `command-line` was a duplicate alias across multiple topics.
This PR removes duplicate aliases and related topics and fixes our tests to prevent regressions going forward. …
> Topics: Remove duplicate aliases and related topics

- collections/government/index.md
The qu project is no longer maintained and has been archived for a year - a great pity. Including it in the list doesn't feel right as bringing it up to date and making it secure is probably a non-trivial task in itself.
> Remove qu as it's archived

- .github/workflows/stale.yml
Adds a GH Action that runs at 12 pm UTC every day to mark PRs that have inactivity for 30 days as stale.
> Add stale action for PRs

- _config.yml
We're using the built in json feed capabilities so we don't currently need this
plugin.
> Remove jekyll feed plugin

- _config.yml
This is needed to make sure that we can build for github pages.
> Exclude vendor directory

- Gemfile
- test/collections_test.rb
- test/test_helper.rb
In this PR:
- add the faraday gem
- add pry
- add a method to fetch and memoize the existing explore json
- add a test to check that the proposed collection changes are the in the same
order as the existing collection items and that new items are appended to the
list.
Why?
- We spend time checking this manually and writing responses to PR authors
when we could just rely on the test to fail
> Test the order of collection items

- topics-todo.md
Signed-off-by: Andy Piper <andypiper@users.noreply.github.com>
The _argo-floats_ and _utility_ topics are now populated, and should have been marked as complete in `topics-todo.md` as part of their respective commits. This small update does exactly that 👍🏻
> Minor: mark argo-floats and utility as done

- .github/workflows/test.yml
- collections/game-engines/index.md
- test/collections_test.rb
- test/test_helper.rb
This PR:
- introduces two new api calls that use the graphql api to check all of the
users/repos in a collection at once and then cache them so we don't make a
single call to the REST api for each item
- Now that we're able to run the tests on the full collection of collections, we've discovered a new repo that has been archived and this PR removes it from the collection it was part of (`CRYTEK/CRYENGINE` in `game-engines`)
> Update api calls to graphql for batching

- test/topics_test.rb
Make range for short description length inclusive so all lengths 1-130 characters are valid
> fix short description length test

- .github/workflows/conflict.yml
---
conflict.yml previously was two jobs, which caused one to be skipped. However, this skipped check showed in the pull UI. With conditional steps instead of conditional jobs, the same checks can be run without a skipped job showing in the UI.
---
> consolidate conflict.yml to a single job with multiple conditional steps

- topics/wiki/index.md
---
> Containing [over 2,800 repositories](https://github.com/topics/wiki), and considering MediaWiki's existence as a [curated topic](https://github.com/topics/mediawiki), I thought it important to also detail the general concept, too. `wiki` makes for a good topic, and, as I've used it, there's good reason for those with an inability to code to still initialize GitHub wikis as a cost-effective way of hosting one's own wiki.
---
> adds wiki as a new topic

- collections/static-site-generators/index.md
Lume is a static site generator for Deno
-   [x]  I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
-   [x]  I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
-   [X]  Suggesting edits to an existing topic or collection
-   [ ]  Curating a new topic or collection
-   [ ]  Something that does not neatly fit into the binary options above
* * * * *
-   [ ]  I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
-   [ ]  My folder contains a `*.png` image (if applicable) and `index.md`
-   [ ]  All required fields in …
> Adding the lume static site generator in list

- topics/error-propagation/index.md
---
For some reason, markdown was rendering single line breaks in the source text as actual line breaks, leading to an improperly formatted topic page:
This pull request simply removes those extraneous line breaks.
---
> Fix line breaks in `error-propagation` topic

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
The goal behind this policy is to prevent people from advertising
a product or a pet project, but the wording restricted _anyone_
with a maintainer/contributor interest in a project from changing
the topic, which was too restrictive. This change makes the wording
more closely aligned with the actual policy.
> Softened language around conflicts of interest

- topics/flathub/index.md
Currently, the description has broken spacing as seen in <https://github.com/topics/flathub>, this PR fixes it by making it continuous.
---
> flathub/index.md: fix broken spacing in description

- collections/react-ui/index.md
Updating `shadcn/ui` to `shadcn-ui/ui` based on failing CI on https://github.com/github/explore/pull/3807
> Update renamed repo

- test/test_helper.rb
Fixing a problem with the tests; it looks like the `MiniTest` casing is no longer supported; since we don't pin any versions of anything, this is causing `bundle exec rake collections` to fail for all other pull requests.
> Fix test_helper.rb

- topics/hacktoberfest/index.md
_I do work at DigitalOcean and am on the core Hacktoberfest team, but per https://github.com/github/explore/pull/3885#issuecomment-1703648392 I'm clear to check this checkbox._
---
I raised some concerns about recent changes to this topic over in https://github.com/github/explore/pull/3995#issuecomment-1810481212, with the tl;dr being that linking out to all these other topics is likely going to be misleading/confusing to participants of Hacktoberfest, as none of these additional topics are endorsed or tracked by Hacktoberfest, so contributions to repositories using them may not be counted if they do not have the `hacktoberfest` topic itself. Further, most of the topics that were added here are essentially not used, with …
> Cleanup Hacktoberfest topic

- topics/minecraft-mod/index.md
---
The `minecraft-modpack` topic has 324 repositories, and `minecraft-modpack` clearly belongs with `minecraft-mod`.
---
> add `minecraft-modpack` alias to `minecraft-mod`

- topics/qt/index.md
---
> Qt5 is already an alias for Qt. This suggests Qt6 should be as well.
> This adds Qt6 as an alias to the existing Qt topic.
---
> Add Qt6 as an alias for Qt

- collections/playdate-rust/index.md
The collection rebuild action in biztools 500s when it hits
this file, with no further info available :(
There are a couple of potential failure points I fixed here:
a bare http url instead of https and a org without a repo listed.
> Fix collections import 500s

- collections/productivity-tools/index.md
---
The Sponsor block and Jump cutter save me a lot of time.
Sponsor block let me skip ads and "integrations" segments embedded in video. According to their stats, i've save 11 days of live for users of Sponsor block:
```
You've saved people from 7,409 segments
( 11d 17h 25.2 minutes of their lives )
You've skipped 2,596 segments ( 2d 9h 16.9 minutes ) 
```
Jump cutter does not have stats, but i think i saved a lot of time on jumps a video fragments with quiet.
So this both browser extension literally save my time. I want to invest couple minutes to add them into public list to share with other people.
---
**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested …
> add SponsorBlock & JumpCutter

- collections/github-browser-extensions/index.md
---
Le Git Graph is a useful extension that can be added to Github and I feel like it deserves a place in this collection.
---
> Add le-git-graph

- collections/javascript-game-engines/index.md
---
I added KAPLAY replacing replit/kaboom due to it's deprecation, also being [KAPLAY mentioned on now replit/kaboom repo ](https://github.com/replit/kaboom?tab=readme-ov-file#notice)
---
> Add kaplayjs/kaplay to JavaScript game engines

- collections/pixel-art-tools/index.md
---
Looks like the Pyxel game engine was mistaken for the PyxelEdit pixel art software, which is not opensource. So I removed it, as the game engine is not a "Pixel Art Tool".
---
> Removed Pyxel game engine

- topics/domain-driven-design/index.md
---
Together, DDD and domain-driven-design have 5k+ repositories
---
> Create topic "DDD"

- topics/finite-state-machine/index.md
---
> Unify all the synonyms (`state-machine` 1,734 repos, `finite-state-machine` 951 repos, `fsm` 780 repos).
---
> Add finite-state-machine topic

- collections/programming-languages/index.md
I am a member of the [julelang organization](https://github.com/julelang).
---
Jule is a general-purpose programming language focusing on systems programming. It aims to be fast, efficient and safe. It has its own set of [goals](https://manual.jule.dev/the-mission.html) and [ideas](https://manual.jule.dev/some-questions.html) that make it original. Jule is being actively developed on GitHub sice 2021.
> Add Jule to the programming laguages collection

- test/test_helper.rb
Return `nil` when a repository is not found rather than raise an octokit error
> Handle not found errors

- Gemfile
- Gemfile.lock
> fix: nokogiri gem update due to security

- topics/misskey/index.md
---
Fastify is changed to NestJS (Fastify is definitely being used, but precisely because Fastify is being used as a backend to NestJS)
And, Because Misskey Frontend uses TypeScript to write its source code
---
> Edit Misskey Description

- .github/workflows/topic-commenter.yml
This unfortunately needs permissions it can't easily get,
in order to run on non-maintainer-submitted PRs. Disabling
until we can work through this in a better way.
> Disable topic checker workflow for now

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/conflict.yml
This had gotten too convoluted and in any case should permit
people to add collection changes for their own projects.
> Simplify and clarify the conflict of interest text

- topics/actions/index.md
- topics/bugbounty/index.md
- topics/casejs/index.md
- topics/chrome/index.md
- topics/composer/index.md
- topics/computercraft-tweaked/index.md
- topics/computercraft/index.md
- topics/conan/index.md
- topics/crud/index.md
- topics/firefox/index.md
- topics/fuzzing/index.md
- topics/hack-and-slash/index.md
- topics/mcnp/index.md
- topics/mozilla/index.md
- topics/opencomputers/index.md
- topics/pip/index.md
- topics/point-and-click/index.md
- topics/portapps/index.md
- topics/prestashop/index.md
- topics/stata/index.md
- topics/ux/index.md
- topics/webextension/index.md
- topics/zeplin/index.md
- topics/zeronet/index.md
> Fix malformed arrays

- topics/zx-spectrum/index.md
---
The Wikipedia article URL for the ZX Spectrum is wrong; it actually goes to the article about action-adventure games. This PR replaces it with the correct URL.
> Fix incorrect Wikipedia link for ZX Spectrum

- collections/game-engines/index.md
---
Stride is one of the largest non-profit open-source game engines, and I was surprised it was missing from this collection.
Adds the repo [`stride3d/stride`](https://github.com/stride3d/stride) to the list.
> Adds Stride3D, the open-source c# game engine

- collections/programming-languages/index.md
*(As a side note which for lack of another communication channel I'm putting here, you seem to require `Signed-off-by` for your commits, but seemingly [the notices have no info](https://github.com/github/explore/blob/4e090821fdddd73a7ccf4e0436e8e89f6cc668ac/notices.md)  on what that means. You don't seem to be using something like the common "Developer Certificate of Origin" for example. I'd like to point out that at least to me, the sign off seems to be ambiguous and potentially pointless, since I feel like it's not really clear what that means to anybody. If it's to accept the licensing and to certify that I wrote the commit, then perhaps the notices should point that out. However, I could be wrong, I'm not a lawyer.)*
--- …
> Update programming-languages collection to allow more projects to join
